---
title: "Week 2 Notes - Algorithmic DecisionMaking & Census Data"
date: "2025-09-15"
---

## Key Concepts Learned
### Algorithmic Decision Making

Algorithm - a set of rules of instruction fir solving a probem or completing a task.

in government - system used to assist/replace human decision-maker based on prediction from models that process historical data:
- input(“features”, “predictors”, “independent variables”, “x”) 
- output (“labels”, “outcome”, “dependent variable”, “y”)

real world - groups of people & individual (systemetical descrimination)

key terms:
- Data Science → Computer science/engineering focus on algorithms and methods

- Data Analytics → Application of data science methods to other disciplines

- Machine Learning → a set of algorithms doing two things: classification & prediction

- AI → Algorithms that adjust and improve across iterations (neural networks, etc.)

### Algorithms go wrong
data analytics is subjective- ivolves human choices, thus embed human values and biases

### Census Data Foundation
census data: 
- every 10 years counting people in the country
american community survey: 
- 3% of household surveyed annually
- 1-year estimates(most current, smallest sample) and 5-year estimate(most reliable, largest sample)
- all acs data with *margins of error*
- summary tables & PUMS-individual records

hierarchy:
county - state and regional planning
- census tracts : 1500-8000 people - neighborhood analysis
-- blocks groups(600-3000 people)
--- blocks(~85 people)

add "noise" to the data to prevent “re-identify” the individuals 

## Coding Techniques
accessing census data in R: use the package "tidycensus"
MOE (margin of error):
- large MOE relative to estimate = less reliable
- small = more reliable
- always report MOE alongside estimates, consider using 5-year estimates fir greater reliability

two formate of output:
- long
- wide: has one row for one id

## Questions & Challenges


## Connections to Policy
###Government use algorithms 
because: long history of goverment data collection + new: more data (also "accidental"), and focus on prediction make it harder to interpret 

advantages: efficiency, consistency, objectivity, cost savings

## Reflection