{
  "hash": "888aab8c43bd126192783b66485297c9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Sihan Yu\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\n\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\n\n# Set Census API key\ncensus_api_key(\"e173851c633e89c20243632174db68f63bac8856\")\n\n# Load spatial data\n\npa_counties <- st_read(here(\"assignments/assignments2/data/Pennsylvania_County_Boundaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `D:\\MUSA5080_Github\\portfolio-setup-sihan-yu429\\assignments\\assignments2\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(here(\"assignments/assignments2/data/hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `D:\\MUSA5080_Github\\portfolio-setup-sihan-yu429\\assignments\\assignments2\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE,, progress_bar = FALSE)\n\n\n# Standardize CRS\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\n\n# check that all data loaded correctly\n\n# Number of hospitals\nn_hospitals <- nrow(hospitals)\n\n\n# Number of census tracts\nn_tracts <- nrow(census_tracts)\n\ncat(\"Number of hospitals:\", nrow(hospitals), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of hospitals: 223 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of census tracts:\", nrow(census_tracts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of census tracts: 3445 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCoordinate Reference Systems (CRS):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCoordinate Reference Systems (CRS):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Counties:\", st_crs(pa_counties)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCounties: WGS 84 / Pseudo-Mercator \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Hospitals:\", st_crs(hospitals)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHospitals: WGS 84 / Pseudo-Mercator \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Census tracts:\", st_crs(census_tracts)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCensus tracts: WGS 84 / Pseudo-Mercator \n```\n\n\n:::\n:::\n\n\n# Check that all data loaded correctly\n\n\n**Questions to answer:**<br>\n-  How many hospitals are in your dataset?<br>\n   There are 223 hospitals in the dataset.<br>\n-  How many census tracts?<br>\n   There are 3445 census tracts.<br>\n-  What coordinate reference system is each dataset in?<br>\n   They share the same coordinate reference system: WGS 84.\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\n#### Step 2: Get Demographic Data ----\n\npa_demo <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  year = 2022,             \n  survey = \"acs5\",\n  variables = c(\n    total_pop = \"B01003_001\",       # Total population\n    median_income = \"B19013_001\",   # Median household income\n    age_65_66 = \"B01001_020\",       # Male 65–66\n    age_67_69 = \"B01001_021\",\n    age_70_74 = \"B01001_022\",\n    age_75_79 = \"B01001_023\",\n    age_80_84 = \"B01001_024\",\n    age_85_plus = \"B01001_025\",\n    f_65_66 = \"B01001_044\",         # Female 65–66\n    f_67_69 = \"B01001_045\",\n    f_70_74 = \"B01001_046\",\n    f_75_79 = \"B01001_047\",\n    f_80_84 = \"B01001_048\",\n    f_85_plus = \"B01001_049\"\n  ),\n  output = \"wide\"\n)\n\n\npa_demo <- pa_demo %>%\n  mutate(\n    pop_65_over = age_65_66E + age_67_69E + age_70_74E + age_75_79E +\n                  age_80_84E + age_85_plusE +\n                  f_65_66E + f_67_69E + f_70_74E + f_75_79E +\n                  f_80_84E + f_85_plusE\n  ) %>%\n  select(GEOID, total_pop = total_popE, median_income = median_incomeE, pop_65_over)\n\n\n\n# Join to tract boundaries\ncensus_tracts_demo <- census_tracts %>%\n  left_join(pa_demo, by = \"GEOID\")\n\n\n# 1. What year of ACS data are you using?\nacs_year <- 2022\ncat(\"ACS Year Used:\", acs_year, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nACS Year Used: 2022 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. How many tracts have missing income data?\nmissing_income <- sum(is.na(census_tracts_demo$median_income))\ncat(\"Number of tracts with missing income data:\", missing_income, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of tracts with missing income data: 62 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. What is the median income across all PA census tracts?\nmedian_income_pa <- median(census_tracts_demo$median_income, na.rm = TRUE)\ncat(\"Median income across all PA census tracts:\", dollar(median_income_pa), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian income across all PA census tracts: $70,188 \n```\n\n\n:::\n:::\n\n\n\n**Questions to answer:**<br>\n-  What year of ACS data are you using?<br>\n   I used data of 2022.<br>\n-  How many tracts have missing income data?<br>\n   There are 62 tracts missing.<br>\n-  What is the median income across all PA census tracts?<br>\n   The medium income across all PA census tracts is $70,188. \n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\nincome_threshold <- quantile(census_tracts_demo$median_income, 0.25, na.rm = TRUE)\nelderly_threshold <- quantile(\n  (census_tracts_demo$pop_65_over / census_tracts_demo$total_pop), \n  0.75, \n  na.rm = TRUE\n)\n\ncat(\"Low-income threshold:\", scales::dollar(income_threshold), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLow-income threshold: $55,923.50 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"High-elderly threshold (share of 65+):\", scales::percent(elderly_threshold), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHigh-elderly threshold (share of 65+): 23% \n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts_demo <- census_tracts_demo %>%\n  mutate(\n    elderly_share = pop_65_over / total_pop\n  )\n\nvulnerable_tracts <- census_tracts_demo %>%\n  filter(\n    median_income <= income_threshold &\n    elderly_share >= elderly_threshold\n  )\ncat(\"Number of vulnerable tracts identified:\", nrow(vulnerable_tracts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of vulnerable tracts identified: 165 \n```\n\n\n:::\n\n```{.r .cell-code}\ntotal_tracts <- nrow(census_tracts_demo)\nvulnerable_count <- nrow(vulnerable_tracts)\nvulnerable_pct <- (vulnerable_count / total_tracts) * 100\ncat(\"Percentage of PA census tracts considered vulnerable:\", round(vulnerable_pct, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of PA census tracts considered vulnerable: 4.8 %\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**<br>\n-  What income threshold did you choose and why?<br>\n   I used $55,923.50 has the income threshold. It is based on the percentiles of the general income data and this is the benchmarks of the bottom 25% of the income across Pennsylvania counties.<br>\n-  What elderly population threshold did you choose and why?<br>\n   I used the same method as for the income threshold. I used the top 25% elderly share(23%) as my threshold. <br>\n-  How many tracts meet your vulnerability criteria?<br>\n   There are 165 tracts meet my vulnerability criteria.<br>\n-  What percentage of PA census tracts are considered vulnerable by your definition?<br>\n   There are 4.8% of PA census tracts that are vulnerable.\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nlibrary(units)\nvulnerable_tracts_proj <- st_transform(vulnerable_tracts, 5070)\nhospitals_proj <- st_transform(hospitals, 5070)\n\ntract_centroids <- st_centroid(vulnerable_tracts_proj)\n# Calculate distance from each tract centroid to nearest hospital\ndist_matrix <- st_distance(tract_centroids, hospitals_proj)\nnearest_hospital_dist_m <- apply(dist_matrix, 1, min)\n\nnearest_hospital_dist_miles <- as.numeric(nearest_hospital_dist_m)/1609.34\n\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(distance_to_hospital_miles = nearest_hospital_dist_miles)\n\navg_distance <- mean(vulnerable_tracts_proj$distance_to_hospital_miles, na.rm = TRUE)\nmax_distance <- max(vulnerable_tracts_proj$distance_to_hospital_miles, na.rm = TRUE)\nnum_over_15 <- sum(vulnerable_tracts_proj$distance_to_hospital_miles > 15, na.rm = TRUE)\n\ncat(\n  \"Average distance to nearest hospital (miles):\", round(avg_distance, 2), \"\\n\",\n  \"Maximum distance to nearest hospital (miles):\", round(max_distance, 2), \"\\n\",\n  \"Number of vulnerable tracts >15 miles from hospital:\", num_over_15, \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage distance to nearest hospital (miles): 4.75 \n Maximum distance to nearest hospital (miles): 19.32 \n Number of vulnerable tracts >15 miles from hospital: 10 \n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**<br>\n-  What is the average distance to the nearest hospital for vulnerable tracts?<br>\n   The average distance is 4.75 miles.<br>\n-  What is the maximum distance?<br>\n   The maximum distance is 19.16 miles.<br>\n-  How many vulnerable tracts are more than 15 miles from the nearest hospital?<br>\n   There are 9 tracts are more than 15 miles from the nearest hospital.\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(underserved = distance_to_hospital_miles > 15)\n\nnum_underserved <- sum(vulnerable_tracts_proj$underserved, na.rm = TRUE)\n\n# Percentage of vulnerable tracts that are underserved\nperc_underserved <- num_underserved / nrow(vulnerable_tracts_proj) * 100\n\ncat(\"Number of underserved tracts:\", num_underserved, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of underserved tracts: 10 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Percentage of vulnerable tracts underserved:\", round(perc_underserved, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of vulnerable tracts underserved: 6.06 %\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**<br>\n-  How many tracts are underserved?<br>\n   There are 9 tracts are underserved.<br>\n-  What percentage of vulnerable tracts are underserved?<br>\n   There are 5.45% of the vulnerable tracts are underserved.<br>\n-  Does this surprise you? Why or why not?<br>\n   It doesn't surprise me. It shows that the hospitals are relatively well_distributed in Pennsylvania that only a small amount of vulnerable tracts are more than 15 miles from the nearest hospital. The few underserved tract are likely in rural areas, however, most of the population concentrated in urban and suburban counties.\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\n\npa_counties_proj <- st_transform(pa_counties, 5070)\n\ntract_centroids <- st_centroid(vulnerable_tracts_proj)\ntract_centroids <- cbind(tract_centroids, vulnerable_tracts_proj)\ntracts_with_county <- st_join(tract_centroids, pa_counties_proj, join = st_within)\n\n# Aggregate statistics by county\ncounty_stats <- tracts_with_county %>%\n  group_by(COUNTY_NAM) %>%          \n  summarise(\n    n_vulnerable_tracts = n(),\n    n_underserved = sum(distance_to_hospital_miles > 15, na.rm = TRUE),\n    pct_underserved = n_underserved / n_vulnerable_tracts * 100,\n    avg_distance_miles = mean(distance_to_hospital_miles, na.rm = TRUE),\n    total_vulnerable_pop = sum(total_pop, na.rm = TRUE)\n  ) %>%\n  arrange(desc(pct_underserved))\n\nst_drop_geometry(county_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 50 × 6\n   COUNTY_NAM n_vulnerable_tracts n_underserved pct_underserved\n * <chr>                    <int>         <int>           <dbl>\n 1 BRADFORD                     1             1           100  \n 2 FOREST                       1             1           100  \n 3 JUNIATA                      1             1           100  \n 4 MONROE                       1             1           100  \n 5 SULLIVAN                     1             1           100  \n 6 CLEARFIELD                   4             2            50  \n 7 DAUPHIN                      2             1            50  \n 8 POTTER                       3             1            33.3\n 9 CRAWFORD                     4             1            25  \n10 ALLEGHENY                   22             0             0  \n# ℹ 40 more rows\n# ℹ 2 more variables: avg_distance_miles <dbl>, total_vulnerable_pop <dbl>\n```\n\n\n:::\n:::\n\n\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**<br>\n-  Which 5 counties have the highest percentage of underserved vulnerable tracts?<br>\n   The 5 counties are Bradford, Forest, Juniata, Monroe, Sullivan.They all have 1 tract that is vulnerable and undeserved.<br>\n-  Which counties have the most vulnerable people living far from hospitals?<br>\n   Allegheny County has the most vulnerable people ~51790 living far from hospitals.<br>\n-  Are there any patterns in where underserved counties are located?<br>\n   The underserved counties are located in northern and central rural Pennsyvania with relatively low population density.\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nlibrary(knitr)\nlibrary(dplyr)\nlibrary(scales)\n\npriority_counties <- county_stats %>%\n  arrange(desc(pct_underserved)) %>%\n  mutate(\n    pct_underserved = round(pct_underserved, 1),\n    avg_distance_miles = round(avg_distance_miles, 1),\n    total_vulnerable_pop = comma(total_vulnerable_pop)\n  ) %>%\n  select(\n    County = COUNTY_NAM,\n    `Vulnerable Tracts` = n_vulnerable_tracts,\n    `Underserved Tracts` = n_underserved,\n    `Underserved (%)` = pct_underserved,\n    `Avg Distance to Hospital (miles)` = avg_distance_miles,\n    `Total Vulnerable Population` = total_vulnerable_pop\n  ) \n\npriority_counties_top10 <- priority_counties %>% slice(1:10)\n\nkable(\n  st_drop_geometry(priority_counties),\n  caption = \"Table: Top 10 Priority Counties for Healthcare Investment in Pennsylvania\",\n  align = \"lccccr\",\n  format = \"pipe\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Table: Top 10 Priority Counties for Healthcare Investment in Pennsylvania\n\n|County         | Vulnerable Tracts | Underserved Tracts | Underserved (%) | Avg Distance to Hospital (miles) | Total Vulnerable Population|\n|:--------------|:-----------------:|:------------------:|:---------------:|:--------------------------------:|---------------------------:|\n|BRADFORD       |         1         |         1          |      100.0      |               16.7               |                       5,466|\n|FOREST         |         1         |         1          |      100.0      |               18.0               |                       2,701|\n|JUNIATA        |         1         |         1          |      100.0      |               16.0               |                       1,782|\n|MONROE         |         1         |         1          |      100.0      |               17.6               |                       1,299|\n|SULLIVAN       |         1         |         1          |      100.0      |               16.9               |                         918|\n|CLEARFIELD     |         4         |         2          |      50.0       |               11.3               |                      13,056|\n|DAUPHIN        |         2         |         1          |      50.0       |               10.0               |                       8,410|\n|POTTER         |         3         |         1          |      33.3       |               9.5                |                       9,062|\n|CRAWFORD       |         4         |         1          |      25.0       |               8.3                |                       9,072|\n|ALLEGHENY      |        22         |         0          |       0.0       |               2.8                |                      51,790|\n|ARMSTRONG      |         1         |         0          |       0.0       |               10.1               |                       2,106|\n|BEAVER         |         5         |         0          |       0.0       |               2.8                |                       9,763|\n|BEDFORD        |         2         |         0          |       0.0       |               8.0                |                       7,578|\n|BLAIR          |         3         |         0          |       0.0       |               3.1                |                       7,602|\n|CAMBRIA        |         6         |         0          |       0.0       |               4.8                |                      13,551|\n|CLARION        |         2         |         0          |       0.0       |               9.3                |                       3,586|\n|CLINTON        |         1         |         0          |       0.0       |               4.9                |                       3,176|\n|CUMBERLAND     |         1         |         0          |       0.0       |               2.0                |                       2,438|\n|DELAWARE       |         1         |         0          |       0.0       |               0.5                |                       2,972|\n|ELK            |         1         |         0          |       0.0       |               10.4               |                       1,557|\n|ERIE           |         4         |         0          |       0.0       |               3.5                |                      12,216|\n|FAYETTE        |         7         |         0          |       0.0       |               4.3                |                      25,230|\n|FRANKLIN       |         2         |         0          |       0.0       |               2.6                |                       7,949|\n|HUNTINGDON     |         1         |         0          |       0.0       |               14.2               |                       2,558|\n|INDIANA        |         2         |         0          |       0.0       |               10.2               |                       5,703|\n|JEFFERSON      |         2         |         0          |       0.0       |               5.6                |                       4,566|\n|LACKAWANNA     |         5         |         0          |       0.0       |               1.8                |                      13,322|\n|LANCASTER      |         1         |         0          |       0.0       |               6.5                |                       4,387|\n|LAWRENCE       |         2         |         0          |       0.0       |               4.4                |                       4,200|\n|LEBANON        |         1         |         0          |       0.0       |               6.3                |                       3,107|\n|LEHIGH         |         1         |         0          |       0.0       |               3.4                |                       3,974|\n|LUZERNE        |         7         |         0          |       0.0       |               3.3                |                      21,062|\n|LYCOMING       |         1         |         0          |       0.0       |               6.8                |                       2,052|\n|MCKEAN         |         3         |         0          |       0.0       |               6.0                |                       7,832|\n|MERCER         |         5         |         0          |       0.0       |               1.8                |                      16,686|\n|MONTGOMERY     |         1         |         0          |       0.0       |               1.3                |                       2,069|\n|NORTHAMPTON    |         3         |         0          |       0.0       |               2.6                |                      10,073|\n|NORTHUMBERLAND |         4         |         0          |       0.0       |               11.2               |                       9,087|\n|PHILADELPHIA   |        16         |         0          |       0.0       |               1.0                |                      61,873|\n|SCHUYLKILL     |         3         |         0          |       0.0       |               2.2                |                      11,194|\n|SOMERSET       |         4         |         0          |       0.0       |               8.4                |                      11,454|\n|SUSQUEHANNA    |         1         |         0          |       0.0       |               5.8                |                       1,612|\n|TIOGA          |         1         |         0          |       0.0       |               0.2                |                       3,459|\n|UNION          |         2         |         0          |       0.0       |               2.6                |                       9,762|\n|VENANGO        |         1         |         0          |       0.0       |               8.1                |                       4,785|\n|WARREN         |         3         |         0          |       0.0       |               6.9                |                       8,041|\n|WASHINGTON     |         3         |         0          |       0.0       |               2.3                |                       5,008|\n|WAYNE          |         1         |         0          |       0.0       |               9.4                |                       2,445|\n|WESTMORELAND   |        11         |         0          |       0.0       |               2.9                |                      25,093|\n|YORK           |         4         |         0          |       0.0       |               1.8                |                      11,199|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nlibrary(ggplot2)\nlibrary(scales)\nlibrary(dplyr)\n\n\npa_counties_map <- pa_counties_proj %>%\n  left_join(\n    priority_counties %>%\n      st_drop_geometry() %>% \n      select(County, `Underserved (%)`),\n    by = c(\"COUNTY_NAM\" = \"County\")\n  )\n\nggplot() +\n  geom_sf(\n    data = pa_counties_map,\n    aes(fill = `Underserved (%)`),\n    color = \"white\", size = 0.25\n  ) +\n  geom_sf(\n    data = hospitals,\n    shape = 21, fill = \"white\", color = \"black\", size = 2, alpha = 0.8\n  ) +\n  scale_fill_viridis_c(\n    option = \"Viridis\",\n    name = \"% Underserved (of vulnerable tracts)\",\n    labels = function(x) paste0(x, \"%\"),\n    na.value = \"grey90\",\n    limits = c(0, 100)\n  ) +\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Percent of vulnerable census tracts that are underserved (>15 miles from nearest hospital)\",\n    caption = \"Sources: ACS 2022 5-year (tidycensus), lecture hospital data, county boundaries\"\n  ) +\n  theme_void() \n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(\n    vulnerable= median_income <= income_threshold &\n                elderly_share >= elderly_threshold\n  ) %>%\n  mutate(\n    tract_status = case_when(\n      vulnerable & underserved ~ \"Underserved & Vulnerable\",\n      vulnerable & !underserved ~ \"Served & Vulnerable\",\n      TRUE ~ \"Other Tracts\"\n  )\n)\n\n  \nggplot()+\n  geom_sf(data = pa_counties_proj, fill = \"grey50\", color = \"white\", size = 0.3) +\n  geom_sf(\n    data = vulnerable_tracts_proj,\n    aes(fill = tract_status),\n    color = NA,\n    alpha = 0.8\n  ) +\n  geom_sf(\n     data = hospitals, shape = 21, fill = \"white\", color = \"black\", size = 2, alpha = 0.8\n  ) +\n  scale_fill_manual(\n    name = \"Tract Status\",\n    values = c(\n      \"Underserved & Vulnerable\" = \"#d7191c\",\n      \"Served & Vulnerable\" = \"#fdae61\",\n      \"Other Tracts\" = \"#cccccc\" \n    )\n  ) +\n  labs(\n    title = \"Underserved Vulnerable Tracts in Pennsylvania\",\n    subtitle = \"Tracts identified as both socially vulnerable and >15 miles from nearest hospital\",\n    caption = \"Sources: ACS 2022 5-year (tidycensus), hospital data, county boundaries\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nggplot(vulnerable_tracts_proj, aes(x = distance_to_hospital_miles)) +\n  geom_histogram(bins = 20, fill = \"#4575b4\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = 15, color = \"#d7191c\", linetype = \"dashed\", size = 1) +\n  labs(\n    title = \"Distribution of Distance to Nearest Hospital for Vulnerable Tracts\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Number of Vulnerable Tracts\",\n    caption = \"Dashed line indicates 15-mile threshold for underserved classification\"\n  ) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nlibrary(sf)\nparks <- st_read(\"PPR_Program_Sites.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PPR_Program_Sites' from data source \n  `D:\\MUSA5080_Github\\portfolio-setup-sihan-yu429\\assignments\\assignments2\\PPR_Program_Sites.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 171 features and 10 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.2563 ymin: 39.90444 xmax: -74.96944 ymax: 40.12284\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nparks <- st_transform(parks, crs = 3857)  # Web Mercator\n\n\nvars <- c(\n  median_income = \"B19013_001\",\n  total_pop = \"B02001_001\",\n  white_pop = \"B02001_002\"\n)\n\nphl_tracts <- get_acs(\n  geography = \"tract\",\n  variables = vars,\n  state = \"PA\",\n  county = \"Philadelphia\",\n  geometry = TRUE,   \n  year = 2023\n) %>%\n  select(GEOID, NAME, variable, estimate, geometry) %>%\n  tidyr::pivot_wider(names_from = variable, values_from = estimate) %>%\n  mutate(\n    minority_share = (total_pop - white_pop) / total_pop * 100\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |================                                                      |  24%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |===================                                                   |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |=====================                                                 |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(phl_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 6 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.24686 ymin: 39.91545 xmax: -75.15233 ymax: 39.94983\nGeodetic CRS:  NAD83\n# A tibble: 6 × 7\n  GEOID       NAME                    geometry total_pop white_pop median_income\n  <chr>       <chr>         <MULTIPOLYGON [°]>     <dbl>     <dbl>         <dbl>\n1 42101001500 Censu… (((-75.16558 39.94366, -…      3027      2213        108378\n2 42101001800 Censu… (((-75.1662 39.94081, -7…      3285      2425        121719\n3 42101002802 Censu… (((-75.16735 39.92658, -…      5868      3525         94427\n4 42101004001 Censu… (((-75.17002 39.92314, -…      4118      3165         82258\n5 42101006300 Censu… (((-75.24686 39.91876, -…      4380        99         32997\n6 42101007700 Censu… (((-75.21292 39.94906, -…      1815      1038         60817\n# ℹ 1 more variable: minority_share <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(trees)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Girth           Height       Volume     \n Min.   : 8.30   Min.   :63   Min.   :10.20  \n 1st Qu.:11.05   1st Qu.:72   1st Qu.:19.40  \n Median :12.90   Median :76   Median :24.20  \n Mean   :13.25   Mean   :76   Mean   :30.17  \n 3rd Qu.:15.25   3rd Qu.:80   3rd Qu.:37.30  \n Max.   :20.60   Max.   :87   Max.   :77.00  \n```\n\n\n:::\n:::\n\n\n\n**Questions to answer:**<br>\n- What dataset did you choose and why?<br>\n  I chose the Philadelphia parks dataset because public parks represent accessible green space for residents. Analyzing their distribution helps assess equity in green space access across different neighborhoods.<br>\n- What is the data source and date?<br>\n  The dataset comes from OpenDataPhilly, specifically the “PPR Program Sites” dataset, most recently updated in 2023.<br>\n- How many features does it contain?<br>\n  The dataset contains 171 park features.<br>\n- What CRS is it in? Did you need to transform it?<br>\n  The parks dataset was originally in WGS84 (EPSG:4326). For consistency with other spatial layers and to facilitate distance and area calculations, I transformed it to EPSG:3857 (Web Mercator projection).\n---\n\n2. **Pose a research question**\n\nDo low-income and minority neighborhoods in Philadelphia have equitable access to green spaces within a 10-minute walk distance?\n\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n# buffer a 0.5 mile distance from the park polygon ~10min\nparks_buffer <- st_buffer(parks, dist = 800)\nparks_buffer <- st_transform(parks_buffer, st_crs(phl_tracts))\n\n\n\n#  Spatial join to identify tracts within 0.5 miles of any park \ncensus_access <- phl_tracts %>%\n  mutate(has_access = lengths(st_intersects(geometry, parks_buffer)) > 0)\n\n# Summary statistics \naccess_summary <- census_access %>%\n  group_by(income_group = case_when(\n    median_income < median(median_income, na.rm = TRUE) ~ \"Low Income\",\n    TRUE ~ \"High Income\"\n  )) %>%\n  summarise(\n    total_tracts = n(),\n    tracts_with_access = sum(has_access),\n    pct_with_access = round(mean(has_access) * 100, 1)\n  )\n\nprint(access_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 2 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.28027 ymin: 39.86705 xmax: -74.95578 ymax: 40.13799\nGeodetic CRS:  NAD83\n# A tibble: 2 × 5\n  income_group total_tracts tracts_with_access pct_with_access\n  <chr>               <int>              <int>           <dbl>\n1 High Income           218                190            87.2\n2 Low Income            190                181            95.3\n# ℹ 1 more variable: geometry <MULTIPOLYGON [°]>\n```\n\n\n:::\n:::\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = census_access, aes(fill = median_income), color = \"white\", size = 0.1) +\n  \n  geom_sf(\n    data = parks_buffer,\n    fill = \"#32CD32\", alpha = 0.25, color = NA\n  ) +\n  \n  geom_sf(\n    data = parks,\n    color = \"#228B22\", size = 1.2\n  ) +\n\n scale_fill_gradientn(\n  name = \"Median Household Income ($)\",\n  colors = c(\"#4575b4\", \"#91bfdb\", \"#fdae61\",\"orange\", \"#d73027\")  # 蓝→浅蓝→浅橙→橙\n  ) +\n  \n  labs(\n    title = \"Philadelphia Census Tracts by Income and Park Accessibility\",\n    subtitle = \"Red shaded areas represent 500 m park buffer zones\",\n    caption = \"Data: OpenDataPhilly Parks, ACS 2021\"\n  ) +\n  \n  theme_minimal() \n```\n\n::: {.cell-output-display}\n![](assignment2_template_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Your interpretation:**\n\nThe table shows that park accessibility is 87.2% in high-income areas and slightly higher at 95.3% in low-income areas, indicating that not all high-income tracts are near parks, though there is a cluster of parks in moderate-income areas in South Philly. Maps show that parks and housing are more concentrated in the city center and low-income areas, while high-income areas in the northwest, northeast, and south are larger but have more dispersed parks. This likely reflects land use and planning: low-density neighborhoods with private yards leave fewer public parks. Overall, park distribution appears influenced more by urban layout and planning than by income alone.\n\n\n## Finally - A few comments about your incorporation of feedback!\nI really appreciated the detailed feedback on my first assignment. It suggested that I clean up unnecessary content and remove figures that didn’t need to be displayed. Following this advice, I tried to clean my Markdown document this time to try to make it look much cleaner and more professional. I hope to continue improving in this way with future assignments.\n\n\n",
    "supporting": [
      "assignment2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}