{
  "hash": "61aff9c885605cb0983113282df49583",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Fire Alarm Prediction-Technical Appendix\"\nauthor:\n  - name: \"Sihan Yu\"\n  - name: \"Isabelle Li\"\n  - name: \"Jingqi Lu\"\n  - name: \"Ming Cao\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    code-fold: true\n    warning: false\n    message: false\neditor: visual\n---\n\n# Introduction\n\nIn the NFIRS (National Fire Incident Reporting System) reporting system, false alarms (codes 700–799) include system malfunctions, unintentional activations, detector errors, and malicious alarms. Although no actual fire is present, each false alarm still triggers a full fire department response.\n\nIn OpenDataPhilly dataset, 77% of all fire-related incidents are false alarms. This extremely high share creates substantial operational burden: every response requires multiple firefighters, apparatus deployment, fuel and equipment usage, and temporarily removes units from availability for real emergencies.\n\nReducing false alarms can save time, reduce firefighter workload, and improve public safety. This analysis produces a predicted probability of false alarm for each incident.\\\nBy choosing an appropriate threshold, the city can identify high-risk cases and apply targeted interventions to reduce unnecessary responses and operational costs.\n\n# Data Preparation\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Core packages\nlibrary(tidyverse)   # dplyr, ggplot2, readr, tidyr, stringr, etc.\nlibrary(sf)\nlibrary(tigris)\nlibrary(tidycensus)\n\n# Modeling / utilities\nlibrary(MASS)\nlibrary(caret)\nlibrary(broom)\nlibrary(patchwork)\nlibrary(scales)\nlibrary(knitr)\nlibrary(riem)\nlibrary(dplyr)\nlibrary(pROC)\nlibrary(tidyr)\nlibrary(lubridate)\n\n# tigris options\noptions(tigris_use_cache = TRUE, tigris_class = \"sf\", tigris_progress = FALSE)\n\n# set a global theme\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## Data Import & Cleaning\n\n### Fire Incident Data\n\nWe recoded incident types following NFIRS conventions. All **7xx** incidents represent *False Alarm & False Call* responses (e.g., alarm system malfunctions, detector errors, accidental activations, and malicious alarms) and were coded as **1**. Incidents in the **1xx** and **2xx** series correspond to actual fires and overpressure/explosion events that required genuine emergency response; these were coded as **0**. This classification provides a clean separation between false alarms and all non–false alarm incidents for modeling purposes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire <- st_read(\"data/stat360/stat360_fire_incidents.shp\", quiet = TRUE)\nsort(table(fire$incident_2), decreasing = TRUE)[1:20]\n\nfire <- fire |>\n  filter(!sf::st_is_empty(geometry)) |>\n  mutate(\n    incident_code = as.integer(str_extract(incident_1, \"^\\\\d+\"))\n  ) |>\n  filter(incident_code %in% c(1L, 7L)) |>\n  mutate(\n    inc_new = if_else(incident_code == 7L, 1L, 0L)\n  )\n\nfire |>\n  st_drop_geometry() |>\n  count(inc_new) |>\n  mutate(p = n / sum(n)) |>\n  knitr::kable(digits = 3)\n```\n:::\n\n\n### Census Data\n\nWe retrieved tract-level demographic and socioeconomic indicators from the 2023 American Community Survey (ACS) to incorporate neighborhood characteristics that may influence false-alarm patterns. Prior research shows that alarm activity often correlates with community demographics, housing conditions, and economic stressors. Accordingly, we included measures of population composition, educational attainment, income, and labor force status to capture these broader social determinants.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly_census <- get_acs(\ngeography = \"tract\",\nvariables = c(\ntotal_pop = \"B01003_001\",\nblack = \"B02001_003\",\nba_degree = \"B15003_022\",\ntotal_edu = \"B15003_001\",\nmedian_income = \"B19013_001\",\nlabor_force = \"B23025_003\",\nunemployed = \"B23025_005\"\n),\nyear = 2023,\nstate = \"PA\",\ncounty = \"Philadelphia\",\ngeometry = TRUE\n) |>\ndplyr::select(GEOID, variable, estimate, geometry) |>\ntidyr::pivot_wider(names_from = variable, values_from = estimate) |>\ndplyr::mutate(\nba_rate = 100 * ba_degree / total_edu,\nunemployment_rate = 100 * unemployed / labor_force,\nblack_share = 100 * black / total_pop\n) |>\nst_transform(st_crs(fire))\n```\n:::\n\n\n### Fire Alarm Data\n\nBuilding certification information comes from the City of Philadelphia’s **Licenses and Inspections (L&I) Building Certifications** dataset on OpenDataPhilly. We joined these records to the building footprints to identify each building’s fire-alarm certification status (Active, Expired, or Deficient). Including this information allows the model to account for building-level inspection and maintenance conditions, which are closely related to false-alarm occurrences.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbldg_foot <- st_read(\"data/LI_BUILDING_FOOTPRINTS.shp\", quiet = TRUE)\ncert_sum <- readr::read_csv(\"data/BUILDING_CERT_SUMMARY.csv\", show_col_types = FALSE)\n\nbldg_cert <- bldg_foot |>\n  mutate(bin = as.character(bin)) |>\n  inner_join(\n    cert_sum |>\n      mutate(structure_id = as.character(structure_id)),\n    by = c(\"bin\" = \"structure_id\")\n  )\n\nbldg_cert |>\n  st_drop_geometry() |>\n  summarise(n_bldg = n_distinct(bin))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n_bldg\n1  26310\n```\n\n\n:::\n\n```{.r .cell-code}\nbldg_cert |>\n  st_drop_geometry() |>\n  count(fire_alarm_status, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  fire_alarm_status     n\n1            Active 13241\n2           Expired  7635\n3              <NA>  5098\n4         Deficient   340\n```\n\n\n:::\n:::\n\n\nWe spatially joined the building certification records to census tracts to summarize inspection conditions at the neighborhood level. For each tract, we calculated the number of buildings with Active, Expired, or Deficient fire-alarm certifications and derived an **active certification rate**. These tract-level indicators were then merged into the ACS dataset, allowing the model to incorporate variation in building inspection status across neighborhoods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbldg_tract <- bldg_cert |>\nst_transform(st_crs(philly_census)) |>\nst_join(philly_census[\"GEOID\"])\n\ntract_alarm <- bldg_tract |>\nst_drop_geometry() |>\ngroup_by(GEOID) |>\nsummarise(\nn_bldg = n(),\nn_active = sum(fire_alarm_status == \"Active\", na.rm = TRUE),\nn_expired = sum(fire_alarm_status == \"Expired\", na.rm = TRUE),\nn_deficient= sum(fire_alarm_status == \"Deficient\", na.rm = TRUE),\nactive_rate = n_active / n_bldg\n)\n\nphilly_census_alarm <- philly_census |>\nleft_join(tract_alarm, by = \"GEOID\")\n```\n:::\n\n\n### Weather Data\n\nWe obtained hourly weather observations from the **PHL airport weather station** using the `riem_measures` API. Data were downloaded in several date ranges and combined into a single dataset, from which duplicate timestamps were removed. Including weather information allows the model to capture environmental conditions such as temperature, precipitation, and wind speed that may influence alarm activations and false-alarm likelihood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_phl <- function(start, end) \n  riem_measures(\n    station     = \"PHL\",\n    date_start  = start,\n    date_end    = end,\n    report_type = c(\"routine\", \"specials\", \"hfmetar\")\n  )\n\nw1 <- get_phl(\"2024-01-01\", \"2024-03-31\")\nw2 <- get_phl(\"2024-04-01\", \"2024-06-30\")\nw3 <- get_phl(\"2024-07-01\", \"2024-09-30\")\nw4 <- get_phl(\"2024-10-01\", \"2024-12-31\")\nw5 <- get_phl(\"2025-01-01\", \"2025-06-30\")\nw6 <- get_phl(\"2025-07-01\", \"2025-10-06\")\n\nweather_data <- bind_rows(w1, w2, w3, w4, w5, w6) |>\n  arrange(valid) |>\n  distinct(valid, .keep_all = TRUE)\n\nrange(weather_data$valid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2024-01-01 00:00:00 UTC\" \"2025-10-05 23:55:00 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(weather_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 196666\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweather_processed <- weather_data %>%\n  dplyr::mutate(\n    interval60    = floor_date(valid, unit = \"hour\"),\n    Temperature   = tmpf,\n    Precipitation = ifelse(is.na(p01i), 0, p01i),\n    Wind_Speed    = sknt\n  ) %>%\n  dplyr::select(interval60, Temperature, Precipitation, Wind_Speed) %>%\n  dplyr::distinct()\n\nweather_complete <- weather_processed %>%\n  tidyr::complete(\n    interval60 = seq(min(interval60), max(interval60), by = \"hour\")\n  ) %>%\n  tidyr::fill(Temperature, Precipitation, Wind_Speed, .direction = \"down\") %>%\n  dplyr::filter(lubridate::hour(interval60) == 12) %>%\n  dplyr::arrange(interval60) %>%\n  dplyr::mutate(date = as.Date(interval60)) %>%\n  dplyr::group_by(date) %>%\n  dplyr::slice(1) %>%\n  dplyr::ungroup() %>%\n  dplyr::select(date, Temperature, Precipitation, Wind_Speed)\n\nweather_complete$Precipitation <- weather_complete$Precipitation + 0.00001\n```\n:::\n\n\n### Work Days and Weekends\n\nFrom the cleaned weather dataset, we generated a day-of-week variable and an `is_weekend` flag to capture weekly temporal patterns in alarm activity. Weekend versus weekday distinctions are included because building use and human activity differ substantially across the week. On weekends, many commercial and institutional buildings operate at reduced occupancy, while residential buildings experience increased activity. These shifts can influence how alarm systems behave through factors such as maintenance schedules, system testing times, building vacancy, cooking activity, or nuisance triggers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweather_daily <- weather_complete %>%\n  dplyr::mutate(\n    dow        = lubridate::wday(date, label = TRUE, week_start = 1),\n    is_weekend = as.integer(dow %in% c(\"Sat\", \"Sun\"))   # 0 = weekday, 1 = weekend\n  )\n\nweather_daily %>%\n  dplyr::count(is_weekend)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  is_weekend     n\n       <int> <int>\n1          0   460\n2          1   184\n```\n\n\n:::\n:::\n\n\n### Location of Fire Stations\n\nWe incorporated the locations of Philadelphia fire stations by converting the `Fire_Dept` table into a spatial dataset using station latitude and longitude. A 100-meter buffer was generated around each station to capture buildings located very close to fire infrastructure. Proximity to a fire station may relate to false-alarm activity, for example, areas near stations may include larger commercial buildings with more alarm systems, more frequent maintenance activity, or higher reporting sensitivity.\n\n\n::: {.cell}\n\n:::\n\n\n## Data Merge\n\nMultiple contextual variables were merged onto the incident dataset to create a comprehensive analytic file. Weather observations were linked by date, fire station buffers were used to generate a proximity indicator, and incidents were spatially joined to census tracts to attach neighborhood socioeconomic and building-inspection attributes. We also derived temporal structure by assigning each incident to a calendar quarter, and calculated the distance from each incident to Philadelphia City Hall as a simple measure of urban centrality. Together, these additions introduce temporal, spatial, and neighborhood-level variation that may influence false-alarm patterns.\n\n### Join Daily Weather to Fire Incidents\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_weather <- fire %>%\n  dplyr::mutate(\n    date = as.Date(alarm_date)  \n  ) %>%\n  dplyr::left_join(\n    weather_daily,\n    by = \"date\"\n  )\n```\n:::\n\n\n### Join the Fire Station Buffer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_weather_station <- fire_weather |>\n  st_transform(st_crs(firesta_buf))\n\nidx <- st_intersects(fire_weather_station, firesta_buf)  \n\nfire_weather_station <- fire_weather_station |>\n  mutate(\n    near_station_200m = as.integer(lengths(idx) > 0) \n  )\n```\n:::\n\n\n### **Combine with Census Tract Data**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly_census_alarm <- philly_census_alarm |>\nst_transform(st_crs(fire_weather_station))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_firetract <- fire_weather_station |>\nst_join(\nphilly_census_alarm,\njoin = st_within, \nleft = TRUE\n)\n```\n:::\n\n\n### Create Quarter Column\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_firetract <- fire_firetract |>\ndplyr::mutate(\nquarter_num = lubridate::quarter(date), # 1–4\nquarter = factor(quarter_num,\nlevels = 1:4,\nlabels = c(\"Q1\", \"Q2\", \"Q3\", \"Q4\"))\n)\n```\n:::\n\n\n### Distance to City Hall\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndowntown <- tribble(\n  ~name, ~lat,       ~lon,\n  \"Philadelphia City Hall (Downtown)\", 39.952583, -75.165222\n) %>%\n  st_as_sf(coords = c(\"lon\",\"lat\"), crs = 4326, remove = FALSE)\n\nn <- nrow(fire_firetract)\n\nfire_firetract <- fire_firetract |>\n  st_transform(st_crs(downtown)) |>\n  mutate(\n    dist_cityhall_m = as.numeric(\n      st_distance(\n        geometry,\n        st_geometry(downtown)[rep(1, n)],\n        by_element = TRUE\n      )\n    ),\n    dist_cityhall_km = dist_cityhall_m / 1000\n  )\n```\n:::\n\n\n# Exploratory Data Analysis\n\n## Map: False Alarm Rate by Census Tract\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntract_fire_stats <- fire_firetract |>\nst_drop_geometry() |>\ndplyr::filter(!is.na(GEOID)) |>\ndplyr::group_by(GEOID) |>\ndplyr::summarise(\nn_incidents  = dplyr::n(),\nn_false_7   = sum(inc_new == 1, na.rm = TRUE),\nfalse_rate_7 = n_false_7 / n_incidents\n)\n\nphilly_census_alarm_fire <- philly_census_alarm |>\ndplyr::left_join(tract_fire_stats, by = \"GEOID\")\n\nggplot(philly_census_alarm_fire) +\n  geom_sf(aes(fill = false_rate_7), color = NA) +\n  scale_fill_viridis_c(\n    option   = \"magma\",\n    direction = -1,\n    na.value = \"grey90\",\n    labels   = scales::percent_format(accuracy = 1),\n    name     = \"False alarm rate\\n(inc_67 share)\"\n  ) +\n  labs(\n    title    = \"False Alarm Rate of Fire Incidents by Census Tract\",\n    subtitle = \"Share of incidents with primary code 7\",\n    caption  = \"Tracts with no incidents shown in grey.\"\n  ) +\n  theme_void() +                        \n  theme(\n    legend.position = \"right\",\n    plot.title      = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Final_Appendix_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nThis map shows the spatial distribution of false alarms across Philadelphia census tracts. Each tract is shaded according to the share of incidents classified as false alarms (primary code 7). Darker purple areas represent neighborhoods where false alarms make up a larger proportion of fire responses, while lighter areas exhibit lower false-alarm activity. Tracts with no recorded incidents during the study period are shown in grey. The pattern highlights substantial geographic variation: several central and high-density neighborhoods display elevated false-alarm rates, whereas some peripheral areas show relatively fewer false responses.\n\n## Pie Chart: True Fire vs False Alarm\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(binary_summary, aes(x = \"\", y = p, fill = fire_type)) +\n  geom_col(width = 1, color = \"white\") +\n  geom_text(\n    aes(label = p_label),\n    position = position_stack(vjust = 0.5),\n    size = 4\n  ) +\n  coord_polar(theta = \"y\") +\n  scale_fill_manual(\n    values = c(\n      \"True Fire\"   = \"lightblue\",\n      \"False Alarm\" = \"hotpink\"\n    )\n  ) +\n  labs(\n    title = \"True Fire vs False Alarm Incidents\",\n    fill  = \"Incident Type\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(\n      hjust = 0.5,\n      size = 14,\n      face = \"bold\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](Final_Appendix_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nThe pie chart summarizes the composition of all fire-related incidents in Philadelphia during the study period. False alarms account for **77%** of all dispatches, while true fire events represent only **23%**. This large imbalance highlights a central operational challenge for the Fire Department: the vast majority of responses do **not** involve an actual fire, yet still require staff time, equipment movement, and system capacity. The high prevalence of false alarms underscores the importance of predictive modeling to help identify where and when such calls are most likely to occur.\n\n## Line Chart: False Alarm Rate by Quarter\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquarter_stats <- fire_firetract |>\n  sf::st_drop_geometry() |>\n  dplyr::filter(!is.na(quarter)) |>\n  dplyr::group_by(quarter) |>\n  dplyr::summarise(\n    n_incidents  = dplyr::n(),\n    false_rate_7 = mean(inc_new == 1, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nggplot(quarter_stats, aes(x = quarter, y = false_rate_7, group = 1)) +\n  geom_line(color = \"hotpink\", size = 1.4) +           \n  geom_point(color = \"hotpink\", size = 3.8) +             \n  geom_text(\n    aes(label = percent(false_rate_7, accuracy = 1)),\n    vjust = -0.6,\n    size = 4,\n    color = \"#2c3e50\"                   \n  ) +\n  scale_y_continuous(\n    labels = percent_format(),\n    limits = c(0.70, 0.84)              \n  ) +\n  labs(\n    title = \"City-wide False Alarm Rate by Quarter\",\n    x = \"Quarter\",\n    y = \"False Alarm Rate\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title = element_text(size = 15, face = \"bold\", hjust = 0.5),\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    axis.text.x = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Final_Appendix_files/figure-html/unnamed-chunk-18-1.png){width=576}\n:::\n:::\n\n\n**Interpretation**\n\nThe quarterly trend shows modest but consistent seasonal variation in Philadelphia’s false alarm rate. Rates rise from **75% in Q1** to a peak of **81% in Q3**, before dropping to **73% in Q4**. This pattern suggests that false alarms become slightly more common during the summer months and decline toward the end of the year. Although the seasonal differences are not dramatic, they highlight that false alarm activity is not evenly distributed across the calendar, which may have implications for staffing, resource planning, and inspection scheduling.\n\n## Map: Expired Alarm Certificates Share by Census Tract\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbldg_cert_flag <- bldg_cert |>\n  filter(!is.na(fire_alarm_status)) |>\n  mutate(\n    alarm_expired = case_when(\n      fire_alarm_status == \"Expired\" ~ 1L,\n      fire_alarm_status %in% c(\"Active\", \"Deficient\") ~ 0L,\n      TRUE ~ NA_integer_\n    )\n  )\n\nbldg_cert_flag <- st_transform(bldg_cert_flag, st_crs(philly_census))\n\nbldg_tract <- st_join(\n  bldg_cert_flag,\n  philly_census |> dplyr::select(GEOID),\n  left = FALSE\n)\n\ntract_expired <- bldg_tract |>\n  st_drop_geometry() |>\n  filter(!is.na(alarm_expired)) |>\n  group_by(GEOID) |>\n  summarise(\n    n_bldg_cert  = n(),\n    expired_share = mean(alarm_expired),\n    .groups = \"drop\"\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntract_map <- philly_census_alarm |>\n  dplyr::left_join(tract_expired, by = \"GEOID\")\n\nggplot(tract_map) +\n  geom_sf(aes(fill = expired_share), color = NA) +\n  scale_fill_viridis_c(\n    option = \"magma\",\n    direction = -1,\n    labels = percent_format(accuracy = 1),\n    na.value = \"grey90\"\n  ) +\n  labs(\n    title = \"Expired Alarm Certificates Share\",\n    fill  = \"Expired Share\"\n  ) +\n  coord_sf(datum = NA) + \n  theme_minimal(base_size = 13) +\n   theme(\n    plot.title      = element_text(face = \"bold\", hjust = 0.5, margin = margin(b = 10)),\n    axis.text       = element_blank(),\n    axis.title      = element_blank(),\n    axis.ticks      = element_blank(),\n    panel.grid      = element_blank(),\n    panel.background = element_rect(fill = \"white\", color = NA),\n    plot.margin     = margin(10, 10, 10, 10)\n  )\n```\n\n::: {.cell-output-display}\n![](Final_Appendix_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nThis map illustrates the share of buildings with **expired fire alarm certifications** across Philadelphia census tracts. Higher-expiry areas (shaded in darker purple) appear in several parts of North and West Philadelphia, as well as pockets of the Northeast. These neighborhoods tend to show a larger proportion of buildings whose annual alarm inspections are overdue, signaling potential maintenance challenges or compliance gaps. In contrast, many tracts in Center City and portions of South Philadelphia display lower expired shares, suggesting stronger inspection adherence. The geographic pattern indicates that certification compliance is not uniform across the city and may align with broader socioeconomic differences, telling us areas where targeted outreach or enforcement may be most needed.\n\n# Modeling\n\n## Model1: Weather Data\n\nModel 1 is a baseline logistic regression that predicts whether an incident is a false alarm (`inc_new = 1`) using only **weather conditions** and **building-level activity rates** on the day of the call. The model includes:\n\n-   **Temperature**: Daily average temperature\n-   **Precipitation**: Total daily precipitation\n-   **Wind_Speed**: Average daily wind speed\n-   **active_rate**: Share of buildings in the tract with an active (valid) fire alarm certification\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model1 <- glm(\n  inc_new ~ Temperature + Precipitation + Wind_Speed + active_rate,\n  data   = fire_firetract,\n  family = binomial(link = \"logit\")\n)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Logistic Regression Model: Weather Predictors Only\n\n|Variable      | Estimate| Std. Error| z value| Pr(>&#124;z&#124;)|\n|:-------------|--------:|----------:|-------:|------------------:|\n|(Intercept)   |   0.5846|     0.0536|   10.91|           0.000000|\n|Temperature   |   0.0101|     0.0005|   18.64|           0.000000|\n|Precipitation |  18.5156|     5.0734|    3.65|           0.000263|\n|Wind_Speed    |   0.0034|     0.0023|    1.44|           0.151000|\n|active_rate   |   0.1182|     0.0810|    1.46|           0.145000|\n\n\n:::\n:::\n\n\nLogit Model 1 serves as the baseline specification, incorporating only weather variables and the building-level alarm compliance rate to predict whether an incident is a false alarm. The model’s estimates indicate statistically significant effects for temperature and precipitation, suggesting that warmer days and days with measurable precipitation are associated with a higher likelihood of false alarms. In contrast, wind speed and the active certification rate do not reach conventional significance levels in this simplified model. Overall model fit is modest, with limited explanatory power relative to later specifications that incorporate socioeconomic, spatial, and temporal predictors. As expected for a parsimonious model, it captures only a small share of the variation in incident outcomes and primarily functions as a reference point against which the performance gains of more complete models can be assessed.\n\n## Model 2: Socioeconomic\n\nModel 2 extends the baseline specification by incorporating census tract–level socioeconomic characteristics to capture structural factors that may influence false alarm patterns. In addition to the weather variables and active building certification rates from Model 1, this model includes:\n\n-   **median_income:** Median household income, reflecting economic resources and potential differences in building conditions. 232qq\n\n-   **ba_rate:** Share of adults holding a bachelor’s degree, used as a proxy for neighborhood socio-demographic composition.\n\n-   **black_share:** Percentage of Black residents in the tract, capturing racial composition patterns relevant for equity analysis.\n\n-   **unemployment_rate:** Local unemployment levels, which may correlate with neighborhood stressors or reporting behaviors.\n\nThese variables allow the model to account for broader socioeconomic context rather than relying solely on incident-day environmental factors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model2 <- glm(\n  inc_new ~ Temperature + Precipitation + Wind_Speed + active_rate +\n    median_income + ba_rate + black_share + unemployment_rate,\n  data   = fire_firetract,\n  family = binomial(link = \"logit\")\n)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Logit Model 2: With Socioeconomic Predictors\n\n|Variable          | Estimate| Std. Error| z value| Pr(>&#124;z&#124;)|\n|:-----------------|--------:|----------:|-------:|------------------:|\n|(Intercept)       |  -1.4270|     0.0740|  -19.29|           0.00e+00|\n|Temperature       |   0.0091|     0.0006|   15.87|           0.00e+00|\n|Precipitation     |  18.3240|     5.2965|    3.46|           5.41e-04|\n|Wind_Speed        |   0.0039|     0.0025|    1.57|           1.16e-01|\n|active_rate       |   0.4680|     0.0888|    5.27|           1.00e-07|\n|median_income     |   0.0000|     0.0000|    5.10|           3.00e-07|\n|ba_rate           |   0.0554|     0.0013|   43.32|           0.00e+00|\n|black_share       |   0.0139|     0.0004|   36.52|           0.00e+00|\n|unemployment_rate |   0.0142|     0.0021|    6.91|           0.00e+00|\n\n\n:::\n:::\n\n\nModel 2 expands the baseline specification by incorporating socioeconomic characteristics of each census tract, and its performance improves substantially relative to Model 1. Education level (ba_rate), Black population share, and median income are highly statistically significant, indicating that false alarm patterns are strongly associated with underlying demographic and socioeconomic conditions. The model’s coefficients suggest that areas with higher educational attainment and larger Black population shares exhibit higher probabilities of false alarms, even after controlling for weather and building-level compliance activity. Compared with the baseline model, the residual deviance decreases from 67133 to 59730 and the AIC drops from 67143 to 59748, indicating a markedly better fit. These gains show that socioeconomic context meaningfully contributes to predicting false alarms and helps explain variation that weather alone cannot.\n\n## Model 3: Full Model\n\nModel 3 extends the previous specifications by incorporating temporal patterns and spatial accessibility factors that may influence the likelihood of a false alarm. In addition to weather, building characteristics, and neighborhood socioeconomic indicators, this model includes:\n\n-   **is_weekend** : Whether the incident occurred on a weekend, capturing changes in occupancy, human activity, and reporting behavior between weekdays and weekends.\n\n-   **quarter**: A categorical indicator for seasonal variation (Q1–Q4), allowing the model to account for cyclical patterns in alarm activity across the year.\n\n-   **near_station_200m**: A binary variable identifying incidents that occur within 200 meters of a fire station, representing potential differences in response environments and built-environment characteristics around stations.\n\n-   **dist_cityhall_km**: The distance from the incident location to Philadelphia City Hall, serving as a proxy for urban centrality and potential differences between high-density downtown areas and more peripheral neighborhoods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model3 <- glm(\n  inc_new ~ Temperature + Precipitation + Wind_Speed + active_rate +\n    median_income + ba_rate + black_share + unemployment_rate +\n    is_weekend + quarter + near_station_200m + dist_cityhall_km,\n  data   = fire_firetract,\n  family = binomial(link = \"logit\")\n)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Logistic Regression Model: Full Model\n\n|Variable          | Estimate| Std. Error| z value| Pr(>&#124;z&#124;)|\n|:-----------------|--------:|----------:|-------:|------------------:|\n|(Intercept)       |  -1.2325|     0.0810|  -15.21|           0.00e+00|\n|Temperature       |   0.0072|     0.0010|    7.45|           0.00e+00|\n|Precipitation     |  17.4394|     5.2598|    3.32|           9.14e-04|\n|Wind_Speed        |   0.0041|     0.0025|    1.65|           9.92e-02|\n|active_rate       |   0.4676|     0.0888|    5.27|           1.00e-07|\n|median_income     |   0.0000|     0.0000|    5.35|           1.00e-07|\n|ba_rate           |   0.0546|     0.0014|   39.33|           0.00e+00|\n|black_share       |   0.0138|     0.0004|   35.71|           0.00e+00|\n|unemployment_rate |   0.0137|     0.0021|    6.66|           0.00e+00|\n|is_weekend        |  -0.0649|     0.0225|   -2.88|           3.92e-03|\n|quarterQ2         |  -0.0305|     0.0369|   -0.83|           4.09e-01|\n|quarterQ3         |   0.0838|     0.0441|    1.90|           5.76e-02|\n|quarterQ4         |  -0.1713|     0.0313|   -5.47|           0.00e+00|\n|near_station_200m |  -0.1063|     0.0308|   -3.45|           5.66e-04|\n|dist_cityhall_km  |  -0.0044|     0.0022|   -1.98|           4.75e-02|\n\n\n:::\n:::\n\n\nThe full model delivers the strongest predictive performance among the three specifications. Adding socioeconomic factors, temporal indicators, and spatial proximity variables substantially improves model fit, reducing deviance and lowering AIC compared to Models 1 and 2. Several predictors show significant associations with false-alarm likelihood, most notably education level, racial composition, unemployment rate, and building certification activity while weather variables retain moderate predictive power. Temporal effects are modest but present, with higher false-alarm rates in Q3 and lower rates in Q4. Spatial features contribute additional explanatory value, as calls nearer to fire stations and farther from Center City are slightly less likely to be false alarms. Overall, the full model captures the most complete set of behavioral, environmental, and geographic signals and therefore serves as the best-performing specification for subsequent interpretation and policy analysis.\n\n## Model Evaluation\n\n### AUC Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1 <- model.frame(logit_model1) \np1   <- predict(logit_model1, type = \"response\")\nroc1 <- roc(dat1$inc_new, p1)\nauc1 <- auc(roc1)\n\ndat2 <- model.frame(logit_model2)\np2   <- predict(logit_model2, type = \"response\")\nroc2 <- roc(dat2$inc_new, p2)\nauc2 <- auc(roc2)\n\ndat3 <- model.frame(logit_model3)\np3   <- predict(logit_model3, type = \"response\")\nroc3 <- roc(dat3$inc_new, p3)\nauc3 <- auc(roc3)\n\ndata.frame(\n  model = c(\"logit_model1\", \"logit_model2\", \"logit_model3\"),\n  AUC   = c(auc1, auc2, auc3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         model       AUC\n1 logit_model1 0.5539505\n2 logit_model2 0.6703993\n3 logit_model3 0.6720569\n```\n\n\n:::\n:::\n\n\nAcross the three logistic regression specifications, predictive performance improves steadily as additional structural, socioeconomic, and temporal features are introduced. Model 1 achieves an AUC of **0.554**, indicating very limited predictive power and only marginal improvement over random guessing. Adding socioeconomic variables in Model 2 substantially increases the AUC to **0.670**, suggesting that neighborhood‐level demographic and income patterns provide meaningful signal in distinguishing false alarms from true fire events. The full model (Model 3), which incorporates temporal indicators, proximity to fire stations, and distance to downtown, yields the highest AUC of **0.672**. Although the improvement over Model 2 is modest, it indicates that these operational and spatial predictors add incremental information beyond weather and socioeconomic structure.\n\n### ROC Curve\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(roc1, col = \"blue\", lwd = 2, main = \"ROC Curves for Logit Models\")\nplot(roc2, col = \"red\", lwd = 2, add = TRUE)\nplot(roc3, col = \"purple\", lwd = 2, add = TRUE)\nlegend(\"bottomright\",\n       legend = c(\"Model 1\", \"Model 2\", \"Model 3\"),\n       col    = c(\"blue\", \"red\", \"purple\"),\n       lwd    = 2)\n```\n\n::: {.cell-output-display}\n![](Final_Appendix_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nThe ROC curves visualize how each model balances sensitivity and specificity across all possible thresholds. Model 1 shows the weakest discrimination, with a curve only slightly above the 45-degree no-skill line. Model 2 improves substantially once socioeconomic characteristics are added, producing a visibly steeper curve. Model 3 offers a modest gain: adding temporal factors and spatial proximity variables produces the strongest curve overall, indicating the most consistent ability to distinguish false alarms from real incidents across thresholds.\n\n### K-fold Cross Validation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\nfire_cv <- fire_firetract |>\n  sf::st_drop_geometry() |>\n  dplyr::mutate(\n    y = ifelse(inc_new == 1, \"FalseAlarm\", \"RealIncident\"),\n    y = factor(y, levels = c(\"FalseAlarm\", \"RealIncident\"))\n  ) |>\n  dplyr::select(\n    y,\n    Temperature, Precipitation, Wind_Speed, active_rate,\n    median_income, ba_rate, black_share, unemployment_rate,\n    is_weekend, quarter, near_station_200m, dist_cityhall_km\n  ) |>\n  tidyr::drop_na()\n\ntrain_control <- trainControl(\n  method = \"cv\",\n  number = 5,\n  classProbs = TRUE,\n  summaryFunction = twoClassSummary\n)\n\nlogit_cv_model <- train(\n  y ~ .,\n  data      = fire_cv,\n  method    = \"glm\",\n  family    = binomial(link = \"logit\"),\n  trControl = train_control,\n  metric    = \"ROC\"\n)\n\nlogit_cv_model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized Linear Model \n\n59340 samples\n   12 predictor\n    2 classes: 'FalseAlarm', 'RealIncident' \n\nNo pre-processing\nResampling: Cross-Validated (5 fold) \nSummary of sample sizes: 47472, 47473, 47471, 47472, 47472 \nResampling results:\n\n  ROC       Sens       Spec      \n  0.671565  0.9858302  0.06613265\n```\n\n\n:::\n:::\n\n\nTo assess the stability of the full logistic regression model, we conduct 5-fold cross-validation on the training data. The cross-validated ROC (0.672) is nearly identical to the in-sample ROC reported earlier, indicating that the model’s predictive performance is highly stable across different data splits. The very high sensitivity and low specificity largely reflect the substantial class imbalance in the outcome (false alarms ≈ 77%). Because classification thresholds are not yet optimized at this stage, these values are not used for model selection; instead, cross-validation primarily confirms that the model generalizes consistently.\n\n### Odds Ratios for Model 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_table_simple <- tidy(logit_model3) %>%\n  mutate(\n    odds_ratio = round(exp(estimate), 3)\n  ) %>%\n  dplyr::select(\n    Variable = term,\n    Odds_Ratio = odds_ratio\n  )\n\nkable(\n  or_table_simple,\n  caption = \"Odds Ratios for Logit Model 3\",\n  align = \"lr\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Odds Ratios for Logit Model 3\n\n|Variable          |   Odds_Ratio|\n|:-----------------|------------:|\n|(Intercept)       |        0.292|\n|Temperature       |        1.007|\n|Precipitation     | 37483869.597|\n|Wind_Speed        |        1.004|\n|active_rate       |        1.596|\n|median_income     |        1.000|\n|ba_rate           |        1.056|\n|black_share       |        1.014|\n|unemployment_rate |        1.014|\n|is_weekend        |        0.937|\n|quarterQ2         |        0.970|\n|quarterQ3         |        1.087|\n|quarterQ4         |        0.843|\n|near_station_200m |        0.899|\n|dist_cityhall_km  |        0.996|\n\n\n:::\n:::\n\n\nThe odds‐ratio table summarizes how each predictor influences the likelihood that an incident is classified as a false alarm after controlling for all other variables. Weather variables, particularly temperature and precipitation, remain strong predictors, with higher temperatures and any measurable precipitation increasing the likelihood of a false alarm. Building compliance also matters: tracts with higher active certification rates show significantly greater odds of false alarms, consistent with patterns observed in the earlier models. Socioeconomic context continues to contribute meaningful signal, higher educational attainment, a larger Black population share, and higher unemployment are all associated with elevated false-alarm odds, even after controlling for weather and temporal factors. Temporal features add smaller but still interpretable effects: false alarms are slightly less likely on weekends and in Q4, and marginally more likely in Q3. Finally, spatial accessibility plays a role: incidents occurring near a fire station (\\<200m) or farther from Center City show modestly reduced odds of being false alarms. Together, these results suggest that false-alarm activity reflects an interaction of environmental conditions, neighborhood characteristics, and system operations.\n\n## Threshold Selection\n\nIn a logistic regression model, predicted values represent the probability that an incident is a false alarm. To convert these probabilities into binary classifications (false alarm vs. real incident), a decision threshold must be chosen. Different thresholds produce different trade-offs between sensitivity (true positive rate) and specificity (true negative rate).\n\nWe evaluated two candidate thresholds—0.9 and 0.4—to illustrate how classification behavior changes under different risk tolerances.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_metrics <- function(th) {\n  pred <- ifelse(p3 >= th, 1L, 0L)\n  cm   <- table(Actual = dat3$inc_new, Pred = pred)\n\n  TN <- cm[\"0\",\"0\"]; FP <- cm[\"0\",\"1\"]\n  FN <- cm[\"1\",\"0\"]; TP <- cm[\"1\",\"1\"]\n\n  tibble(\n    threshold  = th,\n    TN  = as.numeric(TN),\n    FP  = as.numeric(FP),\n    FN  = as.numeric(FN),\n    TP  = as.numeric(TP),\n    accuracy   = (TP + TN) / sum(cm),\n    sensitivity = TP / (TP + FN), \n    specificity = TN / (TN + FP), \n    fpr        = FP / (FP + TN)   \n  )\n}\n\nmetrics <- bind_rows(\n  get_metrics(0.9),\n  get_metrics(0.4)\n)\n\nmetrics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 9\n  threshold    TN    FP    FN    TP accuracy sensitivity specificity    fpr\n      <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl>       <dbl>       <dbl>  <dbl>\n1       0.9 13116   493 42024  3707    0.284      0.0811     0.964   0.0362\n2       0.4    38 13571    23 45708    0.771      0.999      0.00279 0.997 \n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\nThreshold = 0.9 **(Conservative)** A threshold of 0.9 classifies an incident as a false alarm only when the predicted probability is extremely high.\n\n**Very high specificity (96.4%):** almost all true incidents are correctly labeled as real.\n\n**Very low sensitivity (8.1%):** the model fails to identify most false alarms (42,024 false negatives).\n\nThis threshold minimizes false positives but misses the vast majority of false alarms. This setting is appropriate in contexts where misclassifying a real emergency as a false alarm is unacceptable, such as prioritizing safety or enforcement on only the most extreme cases.\n\nThreshold = 0.4 **(Aggressive)** A threshold of 0.4 classifies an incident as a false alarm when the predicted probability exceeds 40%.\n\n**Extremely high sensitivity (99.95%):** nearly all false alarms are detected (only 23 missed).\n\n**Very low specificity (0.28%):** almost all true incidents are incorrectly labeled as false alarms.\n\nThis threshold identifies almost every false alarm but also generates a large number of false positives. This setting is useful in contexts where the goal is to maximize detection, such as broad preventive inspections or outreach.\n\n# Recommendations\n\nThreshold should be chosen based on capacity and goals. Based on the model comparison and operational needs, we recommend adopting a **relatively aggressive threshold** as the decision rule to catch more possible false alarms. Selecting a lower threshold does not imply that the Fire Department will *ignore* these calls; rather, it allows the Department to differentiate levels of risk more effectively. When the model indicates a high likelihood of a false alarm, fire crews would still respond, but they can deploy a **lighter response package**, smaller teams, fewer apparatus, and reduced resource commitment. This minimizes unnecessary operational costs, reduces roadway risk, and preserves capacity for true emergencies. In addition, for calls predicted as likely false alarms, response teams can carry **educational materials, communication guidelines, and basic fire-alarm inspection toolkits**, allowing them to both address the call and engage with property managers about system maintenance and common causes of false activations.\n\nBeyond operational adjustments, we also recommend a set of longer-term policy strategies.\n\nFirst, the City should strengthen **mandatory fire-alarm inspection and compliance enforcement**. For buildings with repeated false alarms or expired certificates, a tiered penalty structure or more frequent re-inspections may create stronger incentives for timely system maintenance.\n\nSecond, the City should expand **public and community education** efforts. The Fire Department could host workshops, property-manager trainings, or community sessions on alarm maintenance, common malfunction causes, and mitigation strategies. Targeted outreach may be especially effective in neighborhoods or buildings with historically high false-alarm rates.\n\n# Limitations&Next Steps\n\n## **Limitations**\n\nAlthough the model provides meaningful predictive ability, it still faces several important limitations. First, the data contain gaps and inconsistencies, for example, missing or outdated fire-alarm certificate records and uneven data quality across neighborhoods which can reduce model stability. Second, because the current model is binary, it can only classify alarms as “false” vs. “not false,” and cannot distinguish different levels of fire risk. No matter how high or low the predicted probability is, the final decision still requires using a single threshold, which restricts how much nuance the model can express. In addition, any misclassification carries real consequences: mislabeling a true fire as a false alarm could delay response, while treating a likely false alarm as high risk may burden residents and property owners and potentially exacerbate existing enforcement inequities. For these reasons, the model should be used as a decision-support tool rather than a substitute for professional judgment.\n\n## **Improvement Possibilities**\n\nWith richer data, more development time, or additional funding, the model could be expanded into a **multi-tier risk classification system**, instead of a simple binary prediction. For example, alarms could be grouped into four levels:\n\n-   Tier 1 = high emergency (very likely real fire)\n\n-   Tier 2 = moderate risk (standard response)\n\n-   Tier 3 = minor risk (non-emergency conditions possible)\n\n-   Tier 4 = high-probability false alarm (light response package)\n\nAchieving this would require integrating additional features, such as alarm device age, building maintenance histories, humidity/smoke environment data, renovation activity, and more granular spatial patterns. These richer inputs would allow the model to shift from hard thresholding to continuous risk scoring and tiered operational strategies, enabling more precise allocation of fire-department resources. Future enhancements could also include multiclass models or time-series analysis to support an even more nuanced and safety-balanced dispatch framework.\n",
    "supporting": [
      "Final_Appendix_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}