{
  "hash": "fa8df623af09e95dad71417e9e99d0f6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Your Name Here\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\n\n# Set Census API key\ncensus_api_key(\"e173851c633e89c20243632174db68f63bac8856\")\n\n# Load spatial data\n\npa_counties <- st_read(here(\"assignments/assignments2/data/Pennsylvania_County_Boundaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `D:\\MUSA5080_Github\\portfolio-setup-sihan-yu429\\assignments\\assignments2\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(here(\"assignments/assignments2/data/hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `D:\\MUSA5080_Github\\portfolio-setup-sihan-yu429\\assignments\\assignments2\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Standardize CRS\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\n\n# check that all data loaded correctly\n\n# Number of hospitals\nn_hospitals <- nrow(hospitals)\nn_hospitals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 223\n```\n\n\n:::\n\n```{.r .cell-code}\n# Number of census tracts\nn_tracts <- nrow(census_tracts)\nn_tracts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3445\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(census_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of hospitals:\", nrow(hospitals), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of hospitals: 223 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of census tracts:\", nrow(census_tracts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of census tracts: 3445 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCoordinate Reference Systems (CRS):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCoordinate Reference Systems (CRS):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Counties:\", st_crs(pa_counties)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCounties: WGS 84 / Pseudo-Mercator \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Hospitals:\", st_crs(hospitals)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHospitals: WGS 84 / Pseudo-Mercator \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Census tracts:\", st_crs(census_tracts)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCensus tracts: WGS 84 / Pseudo-Mercator \n```\n\n\n:::\n:::\n\n\n# Check that all data loaded correctly\n\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset? \n  There are 223 hospitals in the dataset.\n- How many census tracts? \n  There are 3445 census tract.\n- What coordinate reference system is each dataset in?\n  They share the same coordinate reference system as : WGS 84.\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\n#### Step 2: Get Demographic Data ----\n\npa_demo <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  year = 2022,             \n  survey = \"acs5\",\n  variables = c(\n    total_pop = \"B01003_001\",       # Total population\n    median_income = \"B19013_001\",   # Median household income\n    age_65_66 = \"B01001_020\",       # Male 65–66\n    age_67_69 = \"B01001_021\",\n    age_70_74 = \"B01001_022\",\n    age_75_79 = \"B01001_023\",\n    age_80_84 = \"B01001_024\",\n    age_85_plus = \"B01001_025\",\n    f_65_66 = \"B01001_044\",         # Female 65–66\n    f_67_69 = \"B01001_045\",\n    f_70_74 = \"B01001_046\",\n    f_75_79 = \"B01001_047\",\n    f_80_84 = \"B01001_048\",\n    f_85_plus = \"B01001_049\"\n  ),\n  output = \"wide\"\n)\n\n\npa_demo <- pa_demo %>%\n  mutate(\n    pop_65_over = age_65_66E + age_67_69E + age_70_74E + age_75_79E +\n                  age_80_84E + age_85_plusE +\n                  f_65_66E + f_67_69E + f_70_74E + f_75_79E +\n                  f_80_84E + f_85_plusE\n  ) %>%\n  select(GEOID, total_pop = total_popE, median_income = median_incomeE, pop_65_over)\n\n\n\n# Join to tract boundaries\ncensus_tracts_demo <- census_tracts %>%\n  left_join(pa_demo, by = \"GEOID\")\n\n\n# 1. What year of ACS data are you using?\nacs_year <- 2022\ncat(\"ACS Year Used:\", acs_year, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nACS Year Used: 2022 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. How many tracts have missing income data?\nmissing_income <- sum(is.na(census_tracts_demo$median_income))\ncat(\"Number of tracts with missing income data:\", missing_income, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of tracts with missing income data: 62 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. What is the median income across all PA census tracts?\nmedian_income_pa <- median(census_tracts_demo$median_income, na.rm = TRUE)\ncat(\"Median income across all PA census tracts:\", dollar(median_income_pa), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian income across all PA census tracts: $70,188 \n```\n\n\n:::\n:::\n\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n  I used data of 2022.\n- How many tracts have missing income data?\n  There are 62 tracts missing.\n- What is the median income across all PA census tracts?\n  The medium income across all PA census tracts is $70,188. \n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\nincome_threshold <- quantile(census_tracts_demo$median_income, 0.25, na.rm = TRUE)\nelderly_threshold <- quantile(\n  (census_tracts_demo$pop_65_over / census_tracts_demo$total_pop), \n  0.75, \n  na.rm = TRUE\n)\n\ncat(\"Low-income threshold:\", scales::dollar(income_threshold), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLow-income threshold: $55,923.50 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"High-elderly threshold (share of 65+):\", scales::percent(elderly_threshold), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHigh-elderly threshold (share of 65+): 23% \n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts_demo <- census_tracts_demo %>%\n  mutate(\n    elderly_share = pop_65_over / total_pop\n  )\n\nvulnerable_tracts <- census_tracts_demo %>%\n  filter(\n    median_income <= income_threshold &\n    elderly_share >= elderly_threshold\n  )\ncat(\"Number of vulnerable tracts identified:\", nrow(vulnerable_tracts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of vulnerable tracts identified: 165 \n```\n\n\n:::\n\n```{.r .cell-code}\ntotal_tracts <- nrow(census_tracts_demo)\nvulnerable_count <- nrow(vulnerable_tracts)\nvulnerable_pct <- (vulnerable_count / total_tracts) * 100\ncat(\"Percentage of PA census tracts considered vulnerable:\", round(vulnerable_pct, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of PA census tracts considered vulnerable: 4.8 %\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n  I used $55,923.50 has the income threshold. It is based on the percentiles of the general income data and this is the benchmarks of the bottom 25% of the income across Pennsylvania counties.\n- What elderly population threshold did you choose and why?\n  I used the same method as for the income threshold. I used the top 25% elderly share(23%) as my threshold. \n- How many tracts meet your vulnerability criteria?\n  There are 165 tracts meet my vulnerability criteria.\n- What percentage of PA census tracts are considered vulnerable by your definition?\n  There are 4.8% of PA census tracts that are vulnerable.\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nlibrary(units)\nvulnerable_tracts_proj <- st_transform(vulnerable_tracts, 32618)\nhospitals_proj <- st_transform(hospitals, 32618)\n\ntract_centroids <- st_centroid(vulnerable_tracts_proj)\n# Calculate distance from each tract centroid to nearest hospital\ndist_matrix <- st_distance(tract_centroids, hospitals_proj)\nnearest_hospital_dist_m <- apply(dist_matrix, 1, min)\n\nnearest_hospital_dist_miles <- as.numeric(nearest_hospital_dist_m)/1609.34\n\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(distance_to_hospital_miles = nearest_hospital_dist_miles)\n\navg_distance <- mean(vulnerable_tracts_proj$distance_to_hospital_miles, na.rm = TRUE)\nmax_distance <- max(vulnerable_tracts_proj$distance_to_hospital_miles, na.rm = TRUE)\nnum_over_15 <- sum(vulnerable_tracts_proj$distance_to_hospital_miles > 15, na.rm = TRUE)\n\ncat(\n  \"Average distance to nearest hospital (miles):\", round(avg_distance, 2), \"\\n\",\n  \"Maximum distance to nearest hospital (miles):\", round(max_distance, 2), \"\\n\",\n  \"Number of vulnerable tracts >15 miles from hospital:\", num_over_15, \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage distance to nearest hospital (miles): 4.75 \n Maximum distance to nearest hospital (miles): 19.16 \n Number of vulnerable tracts >15 miles from hospital: 9 \n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n  The average distance is 4.75 miles.\n- What is the maximum distance?\n  The maximum distance is 19.16 miles.\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n  There are 9 tracts are more than 15 miles from the nearest hospital.\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(underserved = distance_to_hospital_miles > 15)\n\nnum_underserved <- sum(vulnerable_tracts_proj$underserved, na.rm = TRUE)\n\n# Percentage of vulnerable tracts that are underserved\nperc_underserved <- num_underserved / nrow(vulnerable_tracts_proj) * 100\n\ncat(\"Number of underserved tracts:\", num_underserved, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of underserved tracts: 9 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Percentage of vulnerable tracts underserved:\", round(perc_underserved, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of vulnerable tracts underserved: 5.45 %\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n  There are 9 tracts are underserved.\n- What percentage of vulnerable tracts are underserved?\n  There are 5.45% of the vulnerable tracts are underserved.\n- Does this surprise you? Why or why not?\n  It doesn't surprise me. It shows that the hospitals are relatively well_distributed in Pennsylvania that only a small amount of vulnerable tracts are more than 15 miles from the nearest hospital. The few underserved tract are likely in rural areas, however, most of the population concentrated in urban and suburban counties.\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\npa_counties_proj <- st_transform(pa_counties, st_crs(vulnerable_tracts_proj))\nvulnerable_tracts_county <- st_join(vulnerable_tracts_proj, pa_counties_proj, join = st_within)\n\n# Aggregate statistics by county\ncounty_stats <- vulnerable_tracts_county %>%\n  st_set_geometry(NULL) %>%  # drop geometry for aggregation\n  group_by(NAMELSADCO) %>%          # assuming county name column is \"NAME\"\n  summarise(\n    n_vulnerable_tracts = n(),\n    n_underserved = sum(distance_to_hospital_miles > 15, na.rm = TRUE),\n    pct_underserved = n_underserved / n_vulnerable_tracts * 100,\n    avg_distance_miles = mean(distance_to_hospital_miles, na.rm = TRUE),\n    total_vulnerable_pop = sum(total_pop, na.rm = TRUE)\n  ) %>%\n  arrange(desc(pct_underserved))\n\ncounty_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 50 × 6\n   NAMELSADCO        n_vulnerable_tracts n_underserved pct_underserved\n   <chr>                           <int>         <int>           <dbl>\n 1 Bradford County                     1             1           100  \n 2 Forest County                       1             1           100  \n 3 Juniata County                      1             1           100  \n 4 Monroe County                       1             1           100  \n 5 Sullivan County                     1             1           100  \n 6 Dauphin County                      2             1            50  \n 7 Potter County                       3             1            33.3\n 8 Clearfield County                   4             1            25  \n 9 Crawford County                     4             1            25  \n10 Allegheny County                   22             0             0  \n# ℹ 40 more rows\n# ℹ 2 more variables: avg_distance_miles <dbl>, total_vulnerable_pop <dbl>\n```\n\n\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n  The 5 counties are Bradford, Forest, Juniata, Monroe, Sullivan.\n- Which counties have the most vulnerable people living far from hospitals?\n- Are there any patterns in where underserved counties are located?\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\n```\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n```\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n```\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n```\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n- What is the data source and date?\n- How many features does it contain?\n- What CRS is it in? Did you need to transform it?\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n```\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\n[Write your findings here]\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n\n**File naming:** `LastName_FirstName_Assignment2.html` and `LastName_FirstName_Assignment2.qmd`\n\n---\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}