{
  "hash": "5551327161fba11b89864964a2410da2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 1: Census Data Quality for Policy Decisions\"\nsubtitle: \"Evaluating Data Reliability for Algorithmic Decision-Making\"\nauthor: \"Sihan Yu\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\nexecute:\n  warning: false\n  message: false\n---\n\n# Assignment Overview\n\n## Scenario\n\nYou are a data analyst for the **[Your State] Department of Human Services**. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.\n\nDrawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.\n\n## Learning Objectives\n\n- Apply dplyr functions to real census data for policy analysis\n- Evaluate data quality using margins of error \n- Connect technical analysis to algorithmic decision-making\n- Identify potential equity implications of data reliability issues\n- Create professional documentation for policy stakeholders\n\n## Submission Instructions\n\n**Submit by posting your updated portfolio link on Canvas.** Your assignment should be accessible at `your-portfolio-url/assignments/assignment_1/`\n\nMake sure to update your `_quarto.yml` navigation to include this assignment under an \"Assignments\" menu.\n\n# Part 1: Portfolio Integration\n\nCreate this assignment in your portfolio repository under an `assignments/assignment_1/` folder structure. Update your navigation menu to include:\n\n```\n- text: Assignments\n  menu:\n    - href: assignments/assignment_1/your_file_name.qmd\n      text: \"Assignment 1: Census Data Exploration\"\n```\nIf there is a special character like comma, you need use double quote mark so that the quarto can identify this as text\n\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages (hint: you need tidycensus, tidyverse, and knitr)\nlibrary(tidycensus)\nlibrary(tidyverse)\nlibrary(knitr)\n# Set your Census API key\ncensus_api_key(\"e173851c633e89c20243632174db68f63bac8856\")\n# Choose your state for analysis - assign it to a variable called my_state\nmy_state <- \"New York\"\n```\n:::\n\n\n**State Selection:** I have chosen **New York** for this analysis because: It has a large population, which makes it interesting to study how census data reflects socioeconomic patterns in a large scale.   \n\n# Part 2: County-Level Resource Assessment\n\n## 2.1 Data Retrieval\n\n**Your Task:** Use `get_acs()` to retrieve county-level data for your chosen state.\n\n**Requirements:**\n- Geography: county level\n- Variables: median household income (B19013_001) and total population (B01003_001)  \n- Year: 2022\n- Survey: acs5\n- Output format: wide\n\n**Hint:** Remember to give your variables descriptive names using the `variables = c(name = \"code\")` syntax.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your get_acs() code here\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = c(Median_income = \"B19013_001\",\n                population = \"B01003_001\"\n                ),\n  state = \"NY\",\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\"\n  \n)\n# Clean the county names to remove state name and \"County\" \n# Hint: use mutate() with str_remove()\ncounty_data <- county_data %>%\n  mutate(\n    NAME = NAME %>%\n      str_remove(\", New York\") %>%\n      str_remove(\"County\")\n  )\n# Display the first few rows\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME           Median_incomeE Median_incomeM populationE populationM\n  <chr> <chr>                   <dbl>          <dbl>       <dbl>       <dbl>\n1 36001 \"Albany \"               78829           2049      315041          NA\n2 36003 \"Allegany \"             58725           1965       47222          NA\n3 36005 \"Bronx \"                47036            890     1443229          NA\n4 36007 \"Broome \"               58317           1761      198365          NA\n5 36009 \"Cattaraugus \"          56889           1778       77000          NA\n6 36011 \"Cayuga \"               63227           2736       76171          NA\n```\n\n\n:::\n:::\n\n\n## 2.2 Data Quality Assessment\n\n**Your Task:** Calculate margin of error percentages and create reliability categories.\n\n**Requirements:**\n- Calculate MOE percentage: (margin of error / estimate) * 100\n- Create reliability categories:\n  - High Confidence: MOE < 5%\n  - Moderate Confidence: MOE 5-10%  \n  - Low Confidence: MOE > 10%\n- Create a flag for unreliable estimates (MOE > 10%)\n\n**Hint:** Use `mutate()` with `case_when()` for the categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MOE percentage and reliability categories using mutate()\ncounty_data = county_data %>%\n  mutate(\n    MOE_percentage = (Median_incomeM/Median_incomeE) * 100,\n    reliability = case_when(\n      MOE_percentage < 5 ~\"High confidence\",\n      MOE_percentage < 10 & MOE_percentage >5 ~ \"Moderate confidence\",\n      MOE_percentage >10 ~\"Low confidence\"\n    ),\n    unreliable_flag = if_else(\"MOE percentage\" >10, TRUE, FALSE  )\n )\ncounty_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 62 × 9\n   GEOID NAME           Median_incomeE Median_incomeM populationE populationM\n   <chr> <chr>                   <dbl>          <dbl>       <dbl>       <dbl>\n 1 36001 \"Albany \"               78829           2049      315041          NA\n 2 36003 \"Allegany \"             58725           1965       47222          NA\n 3 36005 \"Bronx \"                47036            890     1443229          NA\n 4 36007 \"Broome \"               58317           1761      198365          NA\n 5 36009 \"Cattaraugus \"          56889           1778       77000          NA\n 6 36011 \"Cayuga \"               63227           2736       76171          NA\n 7 36013 \"Chautauqua \"           54625           1754      127440          NA\n 8 36015 \"Chemung \"              61358           2475       83584          NA\n 9 36017 \"Chenango \"             61741           2526       47096          NA\n10 36019 \"Clinton \"              67097           2802       79839          NA\n# ℹ 52 more rows\n# ℹ 3 more variables: MOE_percentage <dbl>, reliability <chr>,\n#   unreliable_flag <lgl>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Create a summary showing count of counties in each reliability category\n# Hint: use count() and mutate() to add percentages\nlibrary(dplyr)\nlibrary(knitr)\n\nreliability_summary <- county_data %>%\n  count(reliability) %>%                    \n  mutate(percentage = n / sum(n) * 100)     \nreliability_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability             n percentage\n  <chr>               <int>      <dbl>\n1 High confidence        56      90.3 \n2 Low confidence          1       1.61\n3 Moderate confidence     5       8.06\n```\n\n\n:::\n:::\n\n\n## 2.3 High Uncertainty Counties\n\n**Your Task:** Identify the 5 counties with the highest MOE percentages.\n\n**Requirements:**\n- Sort by MOE percentage (highest first)\n- Select the top 5 counties\n- Display: county name, median income, margin of error, MOE percentage, reliability category\n- Format as a professional table using `kable()`\n\n**Hint:** Use `arrange()`, `slice()`, and `select()` functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create table of top 5 counties by MOE percentage\ntop_MOE <- county_data %>%\n  arrange(desc(MOE_percentage)) %>%\n  slice(1:5) %>%\n  select(\n  County = NAME,\n  Median_Income = Median_incomeE,\n  MOE = Median_incomeM,\n  MOE_percentage = MOE_percentage,\n  Reliability = reliability\n  )\n# Format as table with kable() - include appropriate column names and caption\nkable(\n  top_MOE,\n  caption = \"Top 5 Counties with Highest Income MOE Percentage\",\n  col.names = c(\n    \"County\",\n    \"Median Income (Estimate)\",\n    \"Median Income (MOE)\",\n    \"MOE Percentage\",\n    \"Reliability Category\"\n  ),\n  digits = 1 \n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 5 Counties with Highest Income MOE Percentage\n\n|County   | Median Income (Estimate)| Median Income (MOE)| MOE Percentage|Reliability Category |\n|:--------|------------------------:|-------------------:|--------------:|:--------------------|\n|Hamilton |                    66891|                7622|           11.4|Low confidence       |\n|Schuyler |                    61316|                5818|            9.5|Moderate confidence  |\n|Greene   |                    70294|                4341|            6.2|Moderate confidence  |\n|Yates    |                    63974|                3733|            5.8|Moderate confidence  |\n|Essex    |                    68090|                3590|            5.3|Moderate confidence  |\n\n\n:::\n:::\n\n\n**Data Quality Commentary:**\nThe table shows the top 5 counties with relatively high MOE percentages, indicating that the median household income estimates have larger uncertainties. Among them, **Hamilton County** has the highest MOE percentage at 11.4%, suggesting that income data in this county may be less reliable. This could be due to **high income variability** within the county, a relatively **small population**, or the **presence of outliers**. Algorithms that rely on these median income estimates may produce biased or inaccurate decisions in these areas.\n\n\n\n# Part 3: Neighborhood-Level Analysis\n\n## 3.1 Focus Area Selection\n\n**Your Task:** Select 2-3 counties from your reliability analysis for detailed tract-level study.\n\n**Strategy:** Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use filter() to select 2-3 counties from your county_reliability data\n# Store the selected counties in a variable called selected_counties\nmy_counties <- c(\"Orange\", \"Yates\", \"Hamilton\")\nselected_counties <- county_data %>%\n  filter(str_detect(NAME, paste(my_counties, collapse = \"|\")))\n\n# Display the selected counties with their key characteristics\n# Show: county name, median income, MOE percentage, reliability category\nselected_counties %>%\n  select(\n    County = NAME,\n    Median_income = Median_incomeE,\n    MOE_percentage,\n    reliability\n  ) %>%\n  kable(caption = \"Selected Counties with Median Income, MOE %, and Reliability\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Selected Counties with Median Income, MOE %, and Reliability\n\n|County   | Median_income| MOE_percentage|reliability         |\n|:--------|-------------:|--------------:|:-------------------|\n|Hamilton |         66891|      11.394657|Low confidence      |\n|Orange   |         91806|       1.939960|High confidence     |\n|Yates    |         63974|       5.835183|Moderate confidence |\n\n\n:::\n:::\n\n\n**Comment on the output:** Orange County has the highest median income with low MOE percentage, making it has higher reliability. While Yates and Hamilton have lower median incomes and larger MOE percentages, which reduces confidence in their estimates.It is suggests that wealthier counties might has more reliable data.\n\n\n## 3.2 Tract-Level Demographics\n\n**Your Task:** Get demographic data for census tracts in your selected counties.\n\n**Requirements:**\n- Geography: tract level\n- Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001)\n- Use the same state and year as before\n- Output format: wide\n- **Challenge:** You'll need county codes, not names. Look at the GEOID patterns in your county data for hints.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define your race/ethnicity variables with descriptive names\n\nrace = c(\n  White = \"B03002_003\",\n  Black = \"B03002_004\",\n  Hispanic = \"B03002_012\",\n  total_pop =\"B03002_001\"\n  )\n\n# Use get_acs() to retrieve tract-level data\n# Hint: You may need to specify county codes in the county parameter\ntract_data = get_acs(\n  geography = \"tract\",\n  variables = race,\n  state = \"NY\",\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\" \n)\n# Calculate percentage of each group using mutate()\n# Create percentages for white, Black, and Hispanic populations\ntract_data = tract_data %>%\n  mutate(\n    white_p = 100 * WhiteE / total_popE,\n    Black_p = 100 * BlackE / total_popE,\n    Hispanic_p = 100 * HispanicE / total_popE,\n  )\n\n\n# Add readable tract and county name columns using str_extract() or similar\ntract_data <- tract_data %>%\n  mutate(\n    tract_name  = str_replace(NAME, \";\\\\s*[^,]+ County;\\\\s*[^,]+$\", \"\"),\n    county_name = str_extract(NAME, \";\\\\s*[^,]+ County\") %>% \n                  str_remove(\"^;\\\\s*\") %>% \n                  str_remove(\"\\\\s*County$\")                             \n  )\n\nkable(head(tract_data))\n```\n\n::: {.cell-output-display}\n\n\n|GEOID       |NAME                                       | WhiteE| WhiteM| BlackE| BlackM| HispanicE| HispanicM| total_popE| total_popM|  white_p|   Black_p| Hispanic_p|tract_name        |county_name |\n|:-----------|:------------------------------------------|------:|------:|------:|------:|---------:|---------:|----------:|----------:|--------:|---------:|----------:|:-----------------|:-----------|\n|36001000100 |Census Tract 1; Albany County; New York    |    725|    340|    982|    362|       346|       217|       2259|        512| 32.09385| 43.470562|  15.316512|Census Tract 1    |Albany      |\n|36001000201 |Census Tract 2.01; Albany County; New York |    372|    198|   1742|    613|       174|       156|       2465|        608| 15.09128| 70.669371|   7.058823|Census Tract 2.01 |Albany      |\n|36001000202 |Census Tract 2.02; Albany County; New York |    317|    193|   1952|    684|        45|        68|       2374|        668| 13.35299| 82.224094|   1.895535|Census Tract 2.02 |Albany      |\n|36001000301 |Census Tract 3.01; Albany County; New York |    678|    431|   1271|    480|       673|       278|       2837|        581| 23.89848| 44.800846|  23.722242|Census Tract 3.01 |Albany      |\n|36001000302 |Census Tract 3.02; Albany County; New York |   1963|    496|    538|    345|       183|       113|       3200|        500| 61.34375| 16.812500|   5.718750|Census Tract 3.02 |Albany      |\n|36001000401 |Census Tract 4.01; Albany County; New York |   2012|    366|    134|     92|        98|        78|       2301|        399| 87.44024|  5.823555|   4.259018|Census Tract 4.01 |Albany      |\n\n\n:::\n:::\n\n\n## 3.3 Demographic Analysis\n\n**Your Task:** Analyze the demographic patterns in your selected areas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the tract with the highest percentage of Hispanic/Latino residents\n# Hint: use arrange() and slice() to get the top tract\ntop_hispanic <- tract_data %>%\n  filter(county_name %in% my_counties)%>%\n  arrange(desc(Hispanic_p)) %>%\n  slice(1)\n# Calculate average demographics by county using group_by() and summarize()\n# Show: number of tracts, average percentage for each racial/ethnic group\n\ncounty_summary <- tract_data %>%\n  filter(county_name %in% my_counties) %>% \n  group_by(county_name) %>%\n  summarize(\n    num_tracts      = n(),\n    avg_white_pct   = mean(white_p),\n    avg_black_pct   = mean(Black_p),\n    avg_hispanic_pct= mean(Hispanic_p)\n  )\n\n\n# Create a nicely formatted table of your results using kable()\n\nkable(county_summary, caption = \"Average Demographic Percentages by County\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Average Demographic Percentages by County\n\n|county_name | num_tracts| avg_white_pct| avg_black_pct| avg_hispanic_pct|\n|:-----------|----------:|-------------:|-------------:|----------------:|\n|Hamilton    |          4|      91.87527|      1.240264|         2.038062|\n|Orange      |         92|      59.23838|     10.868294|        23.054479|\n|Yates       |          8|      94.17341|      0.520878|         2.116160|\n\n\n:::\n:::\n\n\n# Part 4: Comprehensive Data Quality Evaluation\n\n## 4.1 MOE Analysis for Demographic Variables\n\n**Your Task:** Examine margins of error for demographic variables to see if some communities have less reliable data.\n\n**Requirements:**\n- Calculate MOE percentages for each demographic variable\n- Flag tracts where any demographic variable has MOE > 15%\n- Create summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MOE percentages for white, Black, and Hispanic variables\n# Hint: use the same formula as before (margin/estimate * 100)\ntract_data_filtered <- tract_data %>%\n  filter(WhiteE > 0, BlackE> 0, HispanicE>0)\n\ntract_data_filtered = tract_data_filtered %>%\n  mutate(\n    white_moe = 100 * WhiteM / WhiteE,\n    Black_moe = 100 * BlackM / BlackE,\n    Hispanic_moe = 100 * HispanicM / HispanicE\n  ) %>%\n  filter( \n    white_moe < 100, \n    Black_moe < 100, \n    Hispanic_moe <100\n    )\n\n# Create a flag for tracts with high MOE on any demographic variable\ntract_moe = tract_data_filtered %>% \n  mutate(\n    high_moe = ifelse(\n      white_moe >15 | Black_moe >15 |Hispanic_moe >15, \n      TRUE, FALSE\n    )\n  )\n# Use logical operators (| for OR) in an ifelse() statement\n\n# Create summary statistics showing how many tracts have data quality issues\nsummary <- tract_moe %>%\n  summarize(\n    total_tracts = n(),\n    tracts_high_moe = sum(high_moe),\n    pct_high_moe = (sum(high_moe)/n()*100),\n  )\n\nsummary_county <- tract_moe %>%\n  filter(county_name %in% my_counties)%>%\n  group_by(county_name)%>%\n  summarize(\n    total_tracts = n(),\n    tracts_high_moe = sum(high_moe),\n    pct_high_moe = (sum(high_moe)/n()*100),\n  )\nkable(summary, caption = \"Overall Data Quality: MOE Analysis\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Overall Data Quality: MOE Analysis\n\n| total_tracts| tracts_high_moe| pct_high_moe|\n|------------:|---------------:|------------:|\n|         2669|            2669|          100|\n\n\n:::\n\n```{.r .cell-code}\nsummary_county %>%\n  kable(\n    caption = \"Summary of tracts with high MOE (>15%)\",\n    col.names = c(\"County\", \"N tracts\", \"High-MOE tracts\", \"% High-MOE\")\n  ) \n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of tracts with high MOE (>15%)\n\n|County   | N tracts| High-MOE tracts| % High-MOE|\n|:--------|--------:|---------------:|----------:|\n|Hamilton |        1|               1|        100|\n|Orange   |       68|              68|        100|\n|Yates    |        2|               2|        100|\n\n\n:::\n:::\n\n\n## 4.2 Pattern Analysis\n\n**Your Task:** Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group tracts by whether they have high MOE issues\n# Calculate average characteristics for each group:\n# - population size, demographic percentages\n# Use group_by() and summarize() to create this comparison\n\ntract_moe_changed = tract_data_filtered %>% \n  mutate(\n    high_moe = ifelse(\n      white_moe >50 | Black_moe >50 |Hispanic_moe >50, \n      TRUE, FALSE\n    )\n  )\n\npattern_analysis <- tract_moe_changed %>%\n  mutate(high_moe_flag = ifelse(high_moe, \"High MOE\", \"Low MOE\")) %>%\n  group_by(high_moe_flag) %>%\n  summarize(\n    num_tracts       = n(),\n    avg_population   = mean(total_popE, na.rm = TRUE),\n    avg_white_pct    = mean(WhiteE / total_popE * 100, na.rm = TRUE),\n    avg_black_pct    = mean(BlackE / total_popE * 100, na.rm = TRUE),\n    avg_hispanic_pct = mean(HispanicE / total_popE * 100, na.rm = TRUE)\n  )\n\n\n# Create a professional table showing the patterns\npattern_analysis %>%\n  kable(\n    digits = 1,\n    col.names = c(\"High MOE Flag\", \"N tracts\", \"Avg Pop\", \"Avg % White\", \"Avg % Black\", \"Avg % Hispanic\"),\n    caption = \"Comparison of tract characteristics by data quality group\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of tract characteristics by data quality group\n\n|High MOE Flag | N tracts| Avg Pop| Avg % White| Avg % Black| Avg % Hispanic|\n|:-------------|--------:|-------:|-----------:|-----------:|--------------:|\n|High MOE      |     2141|  3989.4|        47.7|        17.0|           21.5|\n|Low MOE       |      528|  4564.0|        35.3|        25.7|           27.6|\n\n\n:::\n:::\n\n\n**Pattern Analysis:** \nUsing a 15% MOE threshold produced only one group, limiting the ability to compare patterns. To enable analysis, the threshold was adjusted to 50%, yielding two groups: **High MOE** (2141 tracts, ~80%) and **Low MOE** (528 tracts). Yet even under this more lenient criterion, the majority of tracts remain classified as High MOE, highlighting substantial data reliability concerns. Interestingly, these tracts tend to have smaller populations, higher proportions of White residents, and lower proportions of Black and Hispanic residents—patterns that run counter to the initial expectation that more racially diverse areas would exhibit greater uncertainty. Overall, the prevalence of high MOE across most tracts underscores serious data reliability issues.\n\n\n\n# Part 5: Policy Recommendations\n\n## 5.1 Analysis Integration and Professional Summary\n\n**Your Task:** Write an executive summary that integrates findings from all four analyses.\n\n**Executive Summary Requirements:**\n1. **Overall Pattern Identification**: What are the systematic patterns across all your analyses?\n2. **Equity Assessment**: Which communities face the greatest risk of algorithmic bias based on your findings?\n3. **Root Cause Analysis**: What underlying factors drive both data quality issues and bias risk?\n4. **Strategic Recommendations**: What should the Department implement to address these systematic issues?\n\n**Executive Summary:**\nThe analyses reveal consistent geographic and demographic disparities in median income and data quality across counties. Higher-income counties, such as Orange (median income ≈ 91,806), generally show high data reliability and low margins of error (MOE), while lower-income or more rural counties, such as Hamilton (median income ≈ 66,891) and Bronx (≈ 47,036), show moderate-to-low confidence in estimates and higher MOE percentages. Across all tracts, High-MOE areas tend to have smaller populations (≈3,989 per tract on average) and higher percentages of White residents, whereas Low-MOE areas tend to be larger and more diverse.\n\nCommunities at greatest risk of algorithmic bias are not necessarily those county tracts with higher minority percentage, but rather those in small, high-MOE, predominantly White tracts. These high-uncertainty areas are more likely to produce unreliable estimates, meaning that algorithms could allocate resources uneven in less diverse counties. Low-MOE, more diverse tracts are comparatively better represented in the data, which reduces the risk of bias for minority communities.\n\nHigh margins of error (MOE) and data unreliability in New York State are primarily driven by several factors. Population size and demographic homogeneity play a major role: predominantly White, small-population tracts are more likely to exhibit high MOE, amplifying uncertainty for algorithmic applications. Sampling variability further contributes, as rural or low-density areas are harder to survey accurately. Some communities—such as extremely low-income households, residents in rural areas, certain minority populations, and immigrants might have low response rates to the census and surveys, resulting in sparse and uncertain data. Socioeconomic factors, including income levels and population dispersion, also affect the statistical precision of estimates. Additionally, some tracts reporting MOE greater than 100%—highlight the severity of uncertainty, making certain estimates statistically very unreliable and drastically increasing the risk of misrepresentation in algorithms and policy decisions.\n\n**Strategic Recommendations**\n\n1. Enhance Data Collection: Increase survey coverage in high-MOE, low-population tracts to improve the reliability of estimates.\n2. Incorporate MOE in Modeling: Integrate uncertainty measures into algorithmic models to weight outputs appropriately and reduce reliance on potentially biased estimates.\n3. Community Engagement: Encourage participation in surveys and censuses in smaller or rural tracts, particularly among low-income, minority, and immigrant populations, to enhance data completeness and reduce uncertainty.\n\n4. Equity-Focused Resource Allocation: Implement human review for areas with poor data quality; if data reliability is low, do not let algorithms make decisions independently. Pay special attention to high-MOE tracts to prevent misdirected interventions.\n\n## 6.3 Specific Recommendations\n\n**Your Task:** Create a decision framework for algorithm implementation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a summary table using your county reliability data\n# Include: county name, median income, MOE percentage, reliability category\n# Add a new column with algorithm recommendations using case_when():\n# - High Confidence: \"Safe for algorithmic decisions\"\n# - Moderate Confidence: \"Use with caution - monitor outcomes\"  \n# - Low Confidence: \"Requires manual review or additional data\"\ncounty_data <- county_data %>%\n  mutate(\n    algorithm_recommendation = case_when(\n      reliability == \"High confidence\" ~ \"Safe for algorithmic decisions\",\n      reliability == \"Moderate confidence\" ~ \"Use with caution - monitor outcomes\",\n      reliability == \"Low confidence\" ~ \"Requires manual review or additional data\",\n      TRUE ~ \"Unknown\"\n    )\n  )\n\n# Format as a professional table with kable()\n\nsummary_table <- county_data %>%\n  select(county_name = NAME, Median_income = Median_incomeE, MOE_percentage, \n         reliability, algorithm_recommendation)\n\n# Display professional table\nkable(summary_table, \n      caption = \"County-Level Median Income Reliability and Algorithm Recommendations\",\n      col.names = c(\"County\", \"Median Income\", \"MOE (%)\", \"Reliability Category\", \n                    \"Algorithm Recommendation\"),\n      digits = 2)\n```\n\n::: {.cell-output-display}\n\n\nTable: County-Level Median Income Reliability and Algorithm Recommendations\n\n|County       | Median Income| MOE (%)|Reliability Category |Algorithm Recommendation                  |\n|:------------|-------------:|-------:|:--------------------|:-----------------------------------------|\n|Albany       |         78829|    2.60|High confidence      |Safe for algorithmic decisions            |\n|Allegany     |         58725|    3.35|High confidence      |Safe for algorithmic decisions            |\n|Bronx        |         47036|    1.89|High confidence      |Safe for algorithmic decisions            |\n|Broome       |         58317|    3.02|High confidence      |Safe for algorithmic decisions            |\n|Cattaraugus  |         56889|    3.13|High confidence      |Safe for algorithmic decisions            |\n|Cayuga       |         63227|    4.33|High confidence      |Safe for algorithmic decisions            |\n|Chautauqua   |         54625|    3.21|High confidence      |Safe for algorithmic decisions            |\n|Chemung      |         61358|    4.03|High confidence      |Safe for algorithmic decisions            |\n|Chenango     |         61741|    4.09|High confidence      |Safe for algorithmic decisions            |\n|Clinton      |         67097|    4.18|High confidence      |Safe for algorithmic decisions            |\n|Columbia     |         81741|    3.39|High confidence      |Safe for algorithmic decisions            |\n|Cortland     |         65029|    4.42|High confidence      |Safe for algorithmic decisions            |\n|Delaware     |         58338|    3.67|High confidence      |Safe for algorithmic decisions            |\n|Dutchess     |         94578|    2.66|High confidence      |Safe for algorithmic decisions            |\n|Erie         |         68014|    1.18|High confidence      |Safe for algorithmic decisions            |\n|Essex        |         68090|    5.27|Moderate confidence  |Use with caution - monitor outcomes       |\n|Franklin     |         60270|    4.81|High confidence      |Safe for algorithmic decisions            |\n|Fulton       |         60557|    4.37|High confidence      |Safe for algorithmic decisions            |\n|Genesee      |         68178|    4.57|High confidence      |Safe for algorithmic decisions            |\n|Greene       |         70294|    6.18|Moderate confidence  |Use with caution - monitor outcomes       |\n|Hamilton     |         66891|   11.39|Low confidence       |Requires manual review or additional data |\n|Herkimer     |         68104|    4.79|High confidence      |Safe for algorithmic decisions            |\n|Jefferson    |         62782|    3.64|High confidence      |Safe for algorithmic decisions            |\n|Kings        |         74692|    1.27|High confidence      |Safe for algorithmic decisions            |\n|Lewis        |         64401|    4.16|High confidence      |Safe for algorithmic decisions            |\n|Livingston   |         70443|    3.99|High confidence      |Safe for algorithmic decisions            |\n|Madison      |         68869|    4.04|High confidence      |Safe for algorithmic decisions            |\n|Monroe       |         71450|    1.35|High confidence      |Safe for algorithmic decisions            |\n|Montgomery   |         58033|    3.63|High confidence      |Safe for algorithmic decisions            |\n|Nassau       |        137709|    1.39|High confidence      |Safe for algorithmic decisions            |\n|New York     |         99880|    1.78|High confidence      |Safe for algorithmic decisions            |\n|Niagara      |         65882|    2.67|High confidence      |Safe for algorithmic decisions            |\n|Oneida       |         66402|    3.27|High confidence      |Safe for algorithmic decisions            |\n|Onondaga     |         71479|    1.57|High confidence      |Safe for algorithmic decisions            |\n|Ontario      |         76603|    2.94|High confidence      |Safe for algorithmic decisions            |\n|Orange       |         91806|    1.94|High confidence      |Safe for algorithmic decisions            |\n|Orleans      |         61069|    4.89|High confidence      |Safe for algorithmic decisions            |\n|Oswego       |         65054|    3.26|High confidence      |Safe for algorithmic decisions            |\n|Otsego       |         65778|    4.51|High confidence      |Safe for algorithmic decisions            |\n|Putnam       |        120970|    4.03|High confidence      |Safe for algorithmic decisions            |\n|Queens       |         82431|    1.06|High confidence      |Safe for algorithmic decisions            |\n|Rensselaer   |         83734|    2.27|High confidence      |Safe for algorithmic decisions            |\n|Richmond     |         96185|    2.60|High confidence      |Safe for algorithmic decisions            |\n|Rockland     |        106173|    2.88|High confidence      |Safe for algorithmic decisions            |\n|St. Lawrence |         58339|    3.47|High confidence      |Safe for algorithmic decisions            |\n|Saratoga     |         97038|    2.26|High confidence      |Safe for algorithmic decisions            |\n|Schenectady  |         75056|    3.03|High confidence      |Safe for algorithmic decisions            |\n|Schoharie    |         71479|    3.96|High confidence      |Safe for algorithmic decisions            |\n|Schuyler     |         61316|    9.49|Moderate confidence  |Use with caution - monitor outcomes       |\n|Seneca       |         64050|    5.24|Moderate confidence  |Use with caution - monitor outcomes       |\n|Steuben      |         62506|    2.87|High confidence      |Safe for algorithmic decisions            |\n|Suffolk      |        122498|    1.18|High confidence      |Safe for algorithmic decisions            |\n|Sullivan     |         67841|    4.35|High confidence      |Safe for algorithmic decisions            |\n|Tioga        |         70427|    3.99|High confidence      |Safe for algorithmic decisions            |\n|Tompkins     |         69995|    4.01|High confidence      |Safe for algorithmic decisions            |\n|Ulster       |         77197|    4.52|High confidence      |Safe for algorithmic decisions            |\n|Warren       |         74531|    4.74|High confidence      |Safe for algorithmic decisions            |\n|Washington   |         68703|    3.41|High confidence      |Safe for algorithmic decisions            |\n|Wayne        |         71007|    3.10|High confidence      |Safe for algorithmic decisions            |\n|Westchester  |        114651|    1.56|High confidence      |Safe for algorithmic decisions            |\n|Wyoming      |         65066|    3.38|High confidence      |Safe for algorithmic decisions            |\n|Yates        |         63974|    5.84|Moderate confidence  |Use with caution - monitor outcomes       |\n\n\n:::\n:::\n\n\n**Key Recommendations:**\n\n**Your Task:** Use your analysis results to provide specific guidance to the department.\n\n1. **Counties suitable for immediate algorithmic implementation:** \n  Albany, Bronx, Broome, Cattaraugus, Cayuga, Chautauqua, Chemung, Chenango,      Clinton, Columbia, Cortland, Delaware, Dutchess, Erie, Franklin, Fulton,        Genesee, Herkimer, Jefferson, Kings, Lewis, Livingston, Madison, Monroe,        Montgomery, Nassau, New York, Niagara, Oneida, Onondaga, Ontario, Orange,       Orleans, Oswego, Otsego, Putnam, Queens, Rensselaer, Richmond, Rockland, St.    Lawrence, Saratoga, Schenectady, Schoharie, Steuben, Suffolk, Sullivan, Tioga,   Tompkins, Ulster, Warren, Washington, Wayne, Westchester, Wyoming.\n\n  These counties has low MOE that can confidently use thes estiments.\n\n2. **Counties requiring additional oversight:** \n  Essex, Greene, Schuyler, Seneca, Yates\n\n  The counties has moderate confidence data with 5-10% MOE, algorithmic decision   can be used but the outcomes should be monitored. Periodic checks can be used   to examine and ensure the accuracy of predictions.\n\n3. **Counties needing alternative approaches:** \n  Hamilton\n  \n  This county has low confidence and algorithmic decisions are not recommended. Manual review or additional data collection is required.By adding the human oversight that algorithmic outputs can be validated and corrected if needed.\n\n## Questions for Further Investigation\n1. How do spatial patterns in income and demographic distributions affect the reliability of county- and tract-level data? Are there specific geographic clusters with consistently low reliability?\n\n2. What temporal trends or changes over time could be observed if historical ACS survey data were included?\n\n3. How do measurement errors and low survey response rates impact smaller racial or ethnic groups, and what effective safeguards can help prevent bias in algorithmic decisions?\n\n\n# Technical Notes\n\n**Data Sources:** \n- U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates\n- Retrieved via tidycensus R package on 09/20/2025\n\n**Reproducibility:** \n- All analysis conducted in R version [4.5.1]\n- Census API key required for replication\n- Complete code and documentation available at: https://musa-5080-fall-2025.github.io/portfolio-setup-sihan-yu429/assignments/assignments1/scripts/assignment1_template.html\n \n\n**Methodology Notes:**\nSeveral key steps were made during the analysis. Counties were classified into “High,” “Moderate,” and “Low” confidence categories based on ACS income margins of error (MOE), using 5% and 10% cutoffs, where 5% indicates a precise estimate and beyond 10% signals caution. One county was intentionally selected from each reliability category to illustrate contrasts. This approach highlights differences but means specific findings are illustrative. At the tract level, demographic estimates were processed by calculating MOE percentages for racial/ethnic groups, and a 50% MOE flag was applied to identify particularly unreliable tracts. Although the assignment suggested a 15% threshold, using it would flag nearly all tracts, so the higher threshold focuses discussion on the worst data quality issues. These decisions shaped reliability categories and subsequent recommendations, providing conservative but clear examples of high-risk data areas and guiding interpretation of county- and tract-level results.\n\n**Limitations:**\nThe analysis is limited by sample size constraints, especially for smaller racial/ethnic groups at the tract level. This can result in high margins of error. Geographic coverage focuses on selected counties and tracts, so findings may not generalize elsewhere. Temporal scope is limited to the 2018–2022 ACS 5-year estimates, which may not capture rapid changes. Additionally, ACS survey data itself contains inherent inaccuracies due to sampling and nonresponse errors.\n\n---\n\n## Submission Checklist\n\nBefore submitting your portfolio link on Canvas:\n\n- [ ] All code chunks run without errors\n- [ ] All \"[Fill this in]\" prompts have been completed\n- [ ] Tables are properly formatted and readable\n- [ ] Executive summary addresses all four required components\n- [ ] Portfolio navigation includes this assignment\n- [ ] Census API key is properly set \n- [ ] Document renders correctly to HTML\n\n**Remember:** Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at `your-portfolio-url/assignments/assignment_1/your_file_name.html`",
    "supporting": [
      "assignment1_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}