{
  "hash": "aacc1d5c5f6e3731325510669590697f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Philadelphia Housing Model - Technical Appendix\"\nauthor:\n  - name: \"Sihan Yu\"\n  - name: \"Yixuan Li\"\n  - name: \"Jingqi Lu\"\nformat:\n  html:\n    toc: true\n    theme: cosmo\n---\n\n## Phase 1: Data Preparation\n### Load libraries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(tidyverse)\nlibrary(sf)\nlibrary(tidycensus)\nlibrary(knitr)\nlibrary(tigris)\noptions(tigris_use_cache = TRUE, tigris_class = \"sf\")\nlibrary(MASS)\nlibrary(dplyr)\nlibrary(scales)\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(caret)\nlibrary(tibble)\nlibrary(gt)\nlibrary(lm.beta)\nlibrary(broom)\n# Add this near the top of your .qmd after loading libraries\noptions(tigris_use_cache = TRUE)\noptions(tigris_progress = FALSE)  # Suppress tigris progress bars\n```\n:::\n\n\n### Load and clean Philadelphia sales data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nopa <- read_csv(\"data/opa_properties_public.csv\")\n# filter sales (2023 - 2024)\nopa_clean <- opa %>%\n  mutate(sale_date = as.Date(sale_date)) %>%\n  filter(sale_date >= \"2023-01-01\" & sale_date <= \"2024-12-31\")\n# Select relevant variables \nopa_var <- opa_clean %>%\n  dplyr::select(\n    sale_date, sale_price, market_value, building_code_description,\n    total_livable_area, number_of_bedrooms, number_of_bathrooms,\n    number_stories, garage_spaces, central_air, quality_grade,\n    interior_condition, exterior_condition, year_built,\n    zip_code, geographic_ward, census_tract, zoning, owner_1,\n    category_code_description, shape\n  )\n#filter to residential properties(SINGLE FAMILY)\nopa_var <- opa_var %>% \n  filter(category_code_description == \"SINGLE FAMILY\") %>%\n  distinct() %>%\n  filter(\n    !is.na(total_livable_area) & total_livable_area > 0,\n    !is.na(year_built) & year_built > 1800 & year_built <= 2025,\n  )    \n# remove obvious errors & handle missing values, create house age\nopa_var <- opa_var %>%\n  mutate(\n    non_market = ((sale_price / market_value < 0.05) & sale_price < 2000),\n    house_age = 2025 - year_built\n  )\nopa_selected <- opa_var %>% \n  filter(\n    non_market==0\n  )   \nopa_selected <- opa_selected %>%\n  filter(sale_price <= quantile(sale_price, 0.98, na.rm = TRUE))\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to sf object \nopa_sf <- st_as_sf(opa_selected, wkt = \"shape\", crs = 2272) %>%\n  st_transform(4326)\n```\n:::\n\n\n### Load secondary data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load Census data for Philadelphia tracts\nphilly_census <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    black = \"B02001_003\",\n    ba_degree = \"B15003_022\",\n    total_edu = \"B15003_001\",\n    median_income = \"B19013_001\",\n    labor_force = \"B23025_003\",\n    unemployed = \"B23025_005\"\n  ),\n  year = 2023,\n  state = \"PA\",\n  county = \"Philadelphia\",\n  geometry = TRUE\n) %>%\n  dplyr::select(GEOID, variable, estimate, geometry) %>%   # ← 用 dplyr::\n  tidyr::pivot_wider(names_from = variable, values_from = estimate) %>%\n  dplyr::mutate(\n    ba_rate = 100 * ba_degree / total_edu,\n    unemployment_rate = 100 * unemployed / labor_force,\n    black_share = 100 * black/total_pop\n  ) %>%\n  st_transform(st_crs(opa_sf))\n\n# Spatial join of OPA data with Census data\nopa_census <- st_join(opa_sf, philly_census, join = st_within) %>%\n  filter(!is.na(median_income))\n\n#garage dummy\nopa_census <- opa_census %>%\n  mutate(\n    has_garage = if_else(!is.na(garage_spaces) & garage_spaces > 0, 1L, 0L)\n  )\n```\n:::\n\n\n### Summary tables (before/ after)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Original data dimensions\nopa_dims <- tibble(\n  dataset = \"opa (raw CSV)\",\n  rows = nrow(opa),\n  columns = ncol(opa)\n)\n\n# cleaned data dimensions\nopa_filter_dims <- tibble(\n  dataset = \"opa (filtered)\",\n  rows = nrow(opa_clean),\n  columns = ncol(opa_clean)\n)\nopa_selected_dims <- tibble(\n  dataset = \"opa (cleaned & selected)\",\n  rows = nrow(opa_selected),\n  columns = ncol(opa_selected)\n)\n# data dimensions (within census tracts)\nopa_census_dims <- tibble(\n  dataset = \"opa (spatial joined)\",\n  rows = nrow(opa_census),\n  columns = ncol(opa_census)\n)\n\n# create summary table\nsummary_table <- bind_rows(opa_dims, opa_filter_dims,opa_selected_dims, opa_census_dims)\nsummary_table %>%\n  kable(caption = \"Summary of OPA data before and after cleaning\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of OPA data before and after cleaning\n\n|dataset                  |   rows| columns|\n|:------------------------|------:|-------:|\n|opa (raw CSV)            | 583776|      79|\n|opa (filtered)           |  42383|      79|\n|opa (cleaned & selected) |  25860|      23|\n|opa (spatial joined)     |  25585|      35|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the neighborhood data by ward\nwards <- st_read(\"data/Political_Wards.geojson\", quiet = TRUE) %>%\n  st_transform(st_crs(opa_census))\n```\n:::\n\n\n\n### Narrative Explaining Decisions\nDuring the data preparation phase, several cleaning and filtering steps were performed to ensure the reliability of the Philadelphia property sales dataset.\n\n1. **Filtering and selecting relevant variables**  \nOnly single-family residential properties were retained to maintain consistency in property type. Sales were limited to 2023–2024 to focus on the most recent housing market conditions.A subset of relevant columns—such as property characteristics, sale price, and geographic information—was retained to reduce processing time and support exploratory analysis.\n\n2. **Removing obvious errors and handling missing values**  \nExtremely low sale prices—often suspected to be due to inheritance transfers—were excluded to avoid biasing the model. Properties with a reported construction year of “0” were also removed, as these are unrealistic. Similarly, properties with nonpositive living area were excluded, since living area must be greater than zero.\n\n3. **Transforming to spatial format and calculating additional attributes**  \nThe cleaned dataset was then converted to an sf (spatial features) object to enable spatial analysis. An additional variable, house age, was calculated based on the difference between the sale year and the year built, allowing for further filtering of unrealistic building ages and facilitating later modeling steps.\n\n4. **Integrating census and spatial amenity data**  \nCensus tract–level socioeconomic data were obtained via the tidycensus package and spatially joined to the property dataset using st_within(). This ensured that only properties located within the official boundaries of Philadelphia were retained. Additional contextual datasets from OpenDataPhilly (e.g., parks, schools, and public facilities)—were also prepared in phase 3 for subsequent analysis to examine how neighborhood characteristics may influence property prices.\n\n5. **Final dataset summary**  \nThrough this cleaning and integration process, the dataset was reduced from 583,776 initial records to 42,383 after initial filtering, and then to 25,860 after further refinement. Following the spatial join with census tract data, the final analytical dataset contained 25,585 valid property records with complete socioeconomic and spatial information.\n\n## Phase 2: Exploratory Data Analysis\n### 1. Distribution of sale prices (histogram)\n\n::: {.cell}\n\n```{.r .cell-code}\np_raw <- ggplot(opa_var, aes(x = sale_price)) +\n  geom_histogram(bins = 50, fill = \"hotpink\", color = \"black\") +\n  geom_vline(aes(xintercept = median(sale_price)), linetype = \"dashed\") +\n  labs(title = \"Raw Distribution\",\n       x = \"Sale Price\", y = \"Count\") +\n  scale_x_continuous(labels = scales::label_dollar())\np_cut <- opa_census %>%\n  ggplot(aes(x = sale_price)) +\n  geom_histogram(bins = 50, fill = \"skyblue\", color = \"black\") +\n  geom_vline(aes(xintercept = median(sale_price)), linetype = \"dashed\") +\n  labs(title = \"Trimmed Distribution (selected)\",\n       x = \"Sale Price\", y = \"Count\") +\n  scale_x_continuous(labels = scales::label_dollar())\n  \np_raw/p_cut\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nThe first histogram shows the raw distribution of property sale prices in Philadelphia (2023–2024).\nDespite using 50 bins, the distribution remains highly right-skewed, with the vast majority of transactions concentrated below roughly $1.5 million and a small number of luxury properties extending far beyond that range.\nTo address this heavy right tail, we trimmed observations above the 98th percentile of sale prices.\nThis cutoff removes extreme luxury transactions that disproportionately influence the scale, while still preserving over 98% of the housing market.\n\nThe second histogram presents this trimmed distribution, excluding the top 2% of sales.\nAfter removing these extreme outliers, the shape becomes much clearer and more interpretable—revealing a unimodal, approximately log-normal pattern centered around the city’s median sale price.\n\n### 2. Geographic distribution (map)\n\n::: {.cell}\n\n```{.r .cell-code}\nopa_census <- opa_census %>%\n  mutate(price_quartile = ntile(sale_price, 4))\n\nggplot() +\n  geom_sf(data = philly_census, fill = \"lightgrey\", color = \"white\") +\n  geom_sf(data = opa_census, aes(color = factor(price_quartile)), size = 0.1, alpha = 0.7) +\n  scale_color_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    labels = c(\"0%-25%\", \"25%-50%\", \"50%-75%\", \"75%-100%\")\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Housing Sales in Philadelphia (2023–2024)\",\n    color = \"Sale Price Quartile\"\n  )  +\n  guides(color = guide_legend(override.aes = list(size = 3)))\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n**Interpretation**\n\nThe map shows a highly unequal distribution of housing prices across Philadelphia, clearly defined by geography.\n\n**Highest Prices (Deep Purple: 75%-100%)** are heavily clustered in the Northwest (affluent neighborhoods like Chestnut Hill) and the Central/Southeast Core (downtown luxury homes).\n\n**Lowest Prices (Bright Yellow: 0%-25%)** dominate the Southwest portion of the city and parts of the far North/Northeast, indicating the most affordable markets.\n\n**Mid-Range Prices** cover the majority of South Philadelphia and other areas surrounding the high-value core.\n\nIn short, wealth is concentrated in the Northwest and Center City, while affordability is highest in the Southwest.\n\n### 3. Price vs. structural features (scatter plots)\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(opa_census, aes(x = total_livable_area, y = sale_price)) +\n  geom_point(alpha = 0.4, color=\"grey30\") +\n  geom_smooth(method = \"lm\", color = \"darkorange\") +\n  labs(title = \"Sale Price vs. Livable Area\",\n       x = \"Total Livable Area \", y = \"Sale Price\")\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n**Interpretation**\n\nThe scatter plot above shows the relationship between total livable area and sale price for residential properties in Philadelphia (2023–2024).\n\nAs expected, larger homes generally sell for higher prices. However, there is also substantial variation among properties of similar size, reflecting the influence of location, building condition, and neighborhood characteristics.\n\nOverall, this visualization confirms that livable area is positively associated with sale price, though it is not the only factor shaping property values across the city.\n\n### 4. Price vs. spatial features (scatter plots)\n\n::: {.cell}\n\n```{.r .cell-code}\ncrime <- read_csv(\"data/crime.csv\") %>% \n  filter(!is.na(lat) & !is.na(lng)) \ncrime_sf <- st_as_sf(crime, coords = c(\"lng\", \"lat\"), crs = 4326) %>%\n  st_transform(st_crs(opa_census)) \nradius_cri <- 400 \nopa_census$crime_count <- lengths(st_is_within_distance(opa_census, crime_sf, dist = radius_cri)) \n\nggplot(opa_census %>% st_drop_geometry(),\n       aes(x = crime_count, y = sale_price)) +\n  geom_point(alpha = 0.3, color = \"grey60\", size = 1) +\n  geom_smooth(method = \"lm\", color = \"darkorange\", linewidth = 1.2, se = FALSE) +\n  scale_y_continuous(labels = label_dollar()) +\n  labs(\n    title = \"Relationship Between Nearby Crime and Home Sale Price\",\n    subtitle = \"Each point represents a residential property (400m radius crime count)\",\n    x = \"Number of Crimes within 400m\",\n    y = \"Sale Price\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    axis.text = element_text(color = \"grey30\"),\n    axis.title = element_text(color = \"grey20\")\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nopa_interact <- opa_census %>%\n  st_drop_geometry() %>%\n  mutate(\n    unemp_group = ntile(unemployment_rate, 2),\n    unemp_group = factor(unemp_group,\n                         labels = c(\"Low Unemployment\", \"High Unemployment\"))\n  )\n\nggplot(opa_interact, aes(x = crime_count, y = sale_price, color = unemp_group)) +\n  geom_point(alpha = 0.25, size = 0.8) +\n  geom_smooth(method = \"lm\", se = FALSE, linewidth = 1.2) +\n  scale_y_continuous(labels = label_dollar()) +\n  scale_color_viridis_d(option = \"plasma\", direction = -1) +\n  labs(\n    title = \"Interaction: Crime × Unemployment Level\",\n    subtitle = \"Crime has a stronger negative effect in high-unemployment neighborhoods\",\n    x = \"Number of Crimes within 400m\",\n    y = \"Sale Price\",\n    color = \"Unemployment Group\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    legend.position = \"top\",\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nThe first chart shows a pattern in which housing prices fall as nearby crime incidents increase. The second chart shows a situation where high-unemployment areas experience steeper price declines, which means that economic disadvantage amplifies the effect of crime on housing markets.\n\n\n### 5. One creative visualization\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(opa_census %>% st_drop_geometry(),\n       aes(x = house_age, y = sale_price)) +\n  geom_point(alpha = 0.3, color = \"grey60\") +\n  geom_smooth(method = \"loess\", color = \"darkorange\", linewidth = 1.2, se = FALSE) +\n  labs(\n    title = \"House age vs. Sale Price\",\n    x = \"House age\",\n    y = \"Sale Price\"\n  ) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n**Interpretation**\n\nThe chart shows a nonlinear pattern where newer houses sell at higher prices, mid-aged houses experience lower values, and vintage and historical houses regain value due to historic character and prime urban locations.\n\n## Phase 3: Feature Engineering (Technical Appendix)\n\n### 1. Buffer-based features\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load transit stop data and create buffer-based feature\nTransit <- read_csv(\"data/Transit.csv\")\ntransit_sf <- st_as_sf(Transit, coords = c(\"Lon\", \"Lat\"), crs = 4326) %>%\n  st_transform(st_crs(opa_census))\nradius <- 400\nopa_census$transit_count <- lengths(st_is_within_distance(opa_census, transit_sf, dist = radius))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add recreation and parks, create buffer (whithin walking distance)\nrecreation <- read_csv(\"data/recreation.csv\") \nrecreation_sf <- st_as_sf(recreation, coords = c(\"X\", \"Y\"), crs = 4326) %>% st_transform(st_crs(opa_census)) \nradius_rec <- 1200 \nopa_census$recreation_count <- lengths(st_is_within_distance(opa_census, recreation_sf, dist = radius_rec)) \n\n# recreation dummy 0, 1-3, 4-9, 10+\nopa_census$recreation_dummy <- case_when(\n  opa_census$recreation_count == 0 ~ \"None\",\n  opa_census$recreation_count >= 1 & opa_census$recreation_count <= 3 ~ \"Low\",\n  opa_census$recreation_count >= 4 & opa_census$recreation_count <= 8 ~ \"Medium\",\n  opa_census$recreation_count >= 9 ~ \"High\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#add center city as a dummy\ncenter_city <- st_read(\"data/CCD_BOUNDARY.geojson\", quiet = TRUE) %>%\n  st_transform(st_crs(opa_census))\n\nopa_census$center_city_dummy <- as.numeric(\n  lengths(st_intersects(opa_census, center_city)) > 0\n)\n```\n:::\n\n\n\n### 2. k-Nearest Neighbor features\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find the distance of the nearest hospital\nhospital_sf <- st_read(\"data/hospitals.geojson\", quiet = TRUE) %>%\n  st_transform(st_crs(opa_census))\n\nnearest_hospital_index <- st_nearest_feature(opa_census, hospital_sf)\n\nopa_census$nearest_hospital_m <- st_distance(\n  opa_census,\n  hospital_sf[nearest_hospital_index, ],\n  by_element = TRUE\n)\n\nopa_census$nearest_hospital_m <- as.numeric(opa_census$nearest_hospital_m)\n```\n:::\n\n\n\n### 3. Summary table of features\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspatial_summary <- opa_census %>%\n  st_drop_geometry() %>%\n  dplyr::select(crime_count, transit_count, recreation_count, nearest_hospital_m) %>%\n  summarise(\n    across(\n      everything(),\n      list(\n        mean = ~mean(., na.rm = TRUE),\n        median = ~median(., na.rm = TRUE),\n        sd = ~sd(., na.rm = TRUE),\n        min = ~min(., na.rm = TRUE),\n        max = ~max(., na.rm = TRUE)\n      )\n    )\n  ) %>%\n  pivot_longer(\n    cols = everything(),\n    names_to = c(\"variable\", \"stat\"),\n    names_pattern = \"(.*)_(mean|median|sd|min|max)\"\n  ) %>%\n  pivot_wider(names_from = stat, values_from = value) %>%\n  mutate(across(where(is.numeric), ~round(., 2)))\n\nkable(spatial_summary, caption = \"Spatial Summary Statistics\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Spatial Summary Statistics\n\n|variable           |    mean|  median|      sd|   min|     max|\n|:------------------|-------:|-------:|-------:|-----:|-------:|\n|crime_count        |  419.43|  399.00|  289.38|  0.00| 2639.00|\n|transit_count      |   29.50|   25.00|   21.96|  0.00|  216.00|\n|recreation_count   |    3.52|    3.00|    2.24|  0.00|   14.00|\n|nearest_hospital_m | 1794.15| 1607.44| 1015.42| 43.12| 5395.42|\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dummy variable count summary\ndummy_summary <- opa_census %>%\n  st_drop_geometry() %>%\n  dplyr::select(recreation_dummy, center_city_dummy) %>%\n  summarise(across(\n    everything(),\n    ~ paste0(names(table(.)), \": \", as.numeric(table(.))) %>%\n      paste(collapse = \"; \")\n  )) %>%\n  pivot_longer(cols = everything(),\n               names_to = \"variable\",\n               values_to = \"count_distribution\")\n\nkable(dummy_summary, caption = \"Dummy Summary Statistics\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Dummy Summary Statistics\n\n|variable          |count_distribution                               |\n|:-----------------|:------------------------------------------------|\n|recreation_dummy  |High: 823; Low: 12889; Medium: 10774; None: 1099 |\n|center_city_dummy |0: 25295; 1: 290                                 |\n\n\n:::\n:::\n\n**interpretation**\n\n| Feature               | Type        | Description                                      |\n| --------------------- | ----------- | ------------------------------------------------ |\n| `crime_count`         | numeric     | Number of reported crimes within census boundary |\n| `transit_count`       | numeric     | Transit stops within 400 m                       |\n| `recreation_dummy`    | categorical | Accessibility: None / Low / Medium / High        |\n| `nearest_hospital_m`  | numeric     | Distance to nearest hospital (meters)            |\n| `center_city_dummy`   | binary      | 1 = within Center City District                  |\n\n### 4. Narrative Explaining Feature Engineering\n\n**During the feature engineering phase, a series of spatial indicators were developed to capture neighborhood-level conditions relevant to property values across Philadelphia.**\n\n1. **Creating buffer-based accessibility features**  \nTransit stops within a 400 m radius were counted for each property to represent public transport accessibility, a key component of urban connectivity. Recreation facilities within 1.2 km were used to approximate walkable access to amenities under the “15-minute city” concept, which reflects daily life convenience and potentially higher demand in middle- and high-income areas. A categorical variable of recreations was created to classify accessibility as None, Low, Medium, or High.\n\n2. **Adding location dummies and urban core identification**  \nA binary indicator identified whether a property lies within Philadelphia’s Center City boundary. This variable captures the premium effect of the city’s dense commercial and employment core, where housing demand remains consistently high.\n\n3. **Incorporating nearest-neighbor proximity features**  \nThe shortest distance to hospitals was calculated using the k-nearest neighbor approach to represent healthcare accessibility. \n\n\n## Phase 4: Model Building\n### 1. Structural features only\nThis baseline model focuses on property-level characteristics to explain price variation. It includes size, number of bedrooms and bathrooms, and building age (with a quadratic term to capture nonlinear aging effects).\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(sale_price ~ total_livable_area + number_of_bedrooms +\n               number_of_bathrooms + house_age + I(house_age^2),\n             data = opa_census)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + house_age + I(house_age^2), data = opa_census)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1849632   -93819   -16892    62981  1166739 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          2.200e+05  5.906e+03   37.24   <2e-16 ***\ntotal_livable_area   1.598e+02  2.205e+00   72.47   <2e-16 ***\nnumber_of_bedrooms  -3.337e+04  1.200e+03  -27.79   <2e-16 ***\nnumber_of_bathrooms  9.263e+04  1.804e+03   51.34   <2e-16 ***\nhouse_age           -4.486e+03  1.135e+02  -39.52   <2e-16 ***\nI(house_age^2)       2.442e+01  7.249e-01   33.69   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 153500 on 24683 degrees of freedom\n  (896 observations deleted due to missingness)\nMultiple R-squared:  0.4497,\tAdjusted R-squared:  0.4496 \nF-statistic:  4034 on 5 and 24683 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\nThe model shows that larger homes and those with more bathrooms tend to sell for higher prices, while having more bedrooms (holding size constant) slightly reduces value, likely because it implies smaller rooms. Older houses are generally less expensive, but the positive squared term for house age suggests that this decline slows over time—very old or historic homes may retain or regain value. Overall, the model explains about 45% of the variation in sale prices, indicating a reasonably strong fit.\n\n### 2.Census variables\nThis model incorporates neighborhood socioeconomic factors drawn from Census data. Variables such as median income, education level (BA rate), unemployment, and racial composition, which introduce the broader census data context into the housing price model.\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- lm(sale_price ~ total_livable_area + number_of_bedrooms +\n               number_of_bathrooms + house_age + I(house_age^2) +\n               median_income + ba_rate + log(unemployment_rate+1) + black_share,\n             data = opa_census)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + house_age + I(house_age^2) + median_income + \n    ba_rate + log(unemployment_rate + 1) + black_share, data = opa_census)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1494787   -67062   -10215    44754  1241464 \n\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                 2.185e+04  7.125e+03   3.067  0.00217 ** \ntotal_livable_area          1.402e+02  1.891e+00  74.151  < 2e-16 ***\nnumber_of_bedrooms         -6.128e+03  1.059e+03  -5.786 7.29e-09 ***\nnumber_of_bathrooms         6.144e+04  1.569e+03  39.162  < 2e-16 ***\nhouse_age                  -1.999e+03  1.010e+02 -19.788  < 2e-16 ***\nI(house_age^2)              9.349e+00  6.492e-01  14.401  < 2e-16 ***\nmedian_income               1.250e+00  4.665e-02  26.785  < 2e-16 ***\nba_rate                     3.007e+03  1.181e+02  25.462  < 2e-16 ***\nlog(unemployment_rate + 1) -9.702e+03  1.595e+03  -6.082 1.21e-09 ***\nblack_share                -6.888e+02  3.168e+01 -21.742  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 130400 on 24679 degrees of freedom\n  (896 observations deleted due to missingness)\nMultiple R-squared:  0.603,\tAdjusted R-squared:  0.6029 \nF-statistic:  4166 on 9 and 24679 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\nCompared with the first model, this version explains more variation in sale prices (R² rises from 0.45 to 0.60). Structural effects remain similar: larger area and more bathrooms increase value, while older homes are cheaper but the decline slows with age. Adding neighborhood factors improves accuracy—homes in areas with higher income and education levels sell for more, while higher unemployment and larger Black population shares correspond to lower prices. This shows that both property traits and local socioeconomic context shape housing values.\n\n### 3. Spatial features\nThis step adds spatial variables to capture location effects in prices and to improve prediction. We include crime count as safety, transit stops within 400 m as mobility access, recreation within 1.2 km as amenity access, and hospital distance as service access.\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- lm(sale_price ~ total_livable_area + number_of_bedrooms +\n               number_of_bathrooms + house_age + I(house_age^2) +\n               median_income + ba_rate + log(unemployment_rate+1) + black_share +\n               crime_count + I(crime_count^2) + \n               transit_count + recreation_count + nearest_hospital_m + I(nearest_hospital_m^2),\n             data = opa_census)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + house_age + I(house_age^2) + median_income + \n    ba_rate + log(unemployment_rate + 1) + black_share + crime_count + \n    I(crime_count^2) + transit_count + recreation_count + nearest_hospital_m + \n    I(nearest_hospital_m^2), data = opa_census)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1527075   -66187    -9409    45418  1231837 \n\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                 5.774e+04  8.421e+03   6.857 7.18e-12 ***\ntotal_livable_area          1.422e+02  1.898e+00  74.923  < 2e-16 ***\nnumber_of_bedrooms         -5.084e+03  1.062e+03  -4.786 1.71e-06 ***\nnumber_of_bathrooms         5.992e+04  1.563e+03  38.348  < 2e-16 ***\nhouse_age                  -2.037e+03  1.020e+02 -19.972  < 2e-16 ***\nI(house_age^2)              9.206e+00  6.680e-01  13.781  < 2e-16 ***\nmedian_income               1.258e+00  4.712e-02  26.691  < 2e-16 ***\nba_rate                     2.314e+03  1.236e+02  18.727  < 2e-16 ***\nlog(unemployment_rate + 1) -1.272e+04  1.613e+03  -7.886 3.25e-15 ***\nblack_share                -5.942e+02  3.287e+01 -18.076  < 2e-16 ***\ncrime_count                -7.525e+00  8.146e+00  -0.924  0.35559    \nI(crime_count^2)           -1.342e-02  4.434e-03  -3.028  0.00247 ** \ntransit_count               4.535e+02  4.542e+01   9.985  < 2e-16 ***\nrecreation_count            3.766e+03  4.445e+02   8.473  < 2e-16 ***\nnearest_hospital_m         -4.081e+01  3.321e+00 -12.287  < 2e-16 ***\nI(nearest_hospital_m^2)     8.112e-03  7.117e-04  11.398  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 129400 on 24673 degrees of freedom\n  (896 observations deleted due to missingness)\nMultiple R-squared:  0.6092,\tAdjusted R-squared:  0.6089 \nF-statistic:  2564 on 15 and 24673 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\nThis third model adds spatial accessibility and amenity variables on top of housing and neighborhood characteristics. The explanatory power improves slightly (R² rises from 0.60 to 0.61). Core structural effects remain consistent: larger homes and more bathrooms raise prices, while older homes are cheaper but depreciate more slowly with age.\n\nAmong the new variables, transit access and recreation facilities show strong positive effects—areas with better public transport and more recreation sites have higher housing values. Proximity to hospitals also matters: prices fall as distance increases, but the positive squared term suggests diminishing marginal effects once the hospital is very close. Crime count is mostly insignificant, implying limited direct influence after controlling for other neighborhood factors.\n\n### 4. Interactions and fixed effects\nThis final model adds interaction and dummy variables to capture more detailed relationships. The interaction term between crime count and unemployment rate examines how the effect of crime varies with local economic conditions. Dummy variables identify categorical differences: has_garage explains the house stucture, center_city_dummy represents the city core premium, and recreation_dummy classifies recreational access levels.\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4 <- lm(sale_price ~ total_livable_area + number_of_bedrooms +number_of_bathrooms +\n               house_age + I(house_age^2) +\n               median_income + ba_rate + crime_count*unemployment_rate + black_share + \n               has_garage + center_city_dummy + recreation_dummy + \n               transit_count + nearest_hospital_m + I(nearest_hospital_m^2),\n             data = opa_census)\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + house_age + I(house_age^2) + median_income + \n    ba_rate + crime_count * unemployment_rate + black_share + \n    has_garage + center_city_dummy + recreation_dummy + transit_count + \n    nearest_hospital_m + I(nearest_hospital_m^2), data = opa_census)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1483816   -65681   -10090    44396  1232825 \n\nCoefficients:\n                                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                    1.121e+05  9.380e+03  11.951  < 2e-16 ***\ntotal_livable_area             1.398e+02  1.898e+00  73.628  < 2e-16 ***\nnumber_of_bedrooms            -4.858e+03  1.065e+03  -4.561 5.11e-06 ***\nnumber_of_bathrooms            5.975e+04  1.563e+03  38.237  < 2e-16 ***\nhouse_age                     -2.139e+03  1.015e+02 -21.065  < 2e-16 ***\nI(house_age^2)                 1.053e+01  6.654e-01  15.828  < 2e-16 ***\nmedian_income                  1.259e+00  4.633e-02  27.173  < 2e-16 ***\nba_rate                        2.406e+03  1.248e+02  19.273  < 2e-16 ***\ncrime_count                   -4.881e+01  5.850e+00  -8.343  < 2e-16 ***\nunemployment_rate             -3.039e+03  3.326e+02  -9.136  < 2e-16 ***\nblack_share                   -5.554e+02  3.257e+01 -17.056  < 2e-16 ***\nhas_garage                     2.167e+04  2.065e+03  10.494  < 2e-16 ***\ncenter_city_dummy              3.268e+04  9.776e+03   3.343 0.000831 ***\nrecreation_dummyLow           -5.425e+04  4.947e+03 -10.967  < 2e-16 ***\nrecreation_dummyMedium        -4.568e+04  4.897e+03  -9.327  < 2e-16 ***\nrecreation_dummyNone          -7.618e+04  6.353e+03 -11.990  < 2e-16 ***\ntransit_count                  4.257e+02  4.729e+01   9.002  < 2e-16 ***\nnearest_hospital_m            -4.213e+01  3.313e+00 -12.717  < 2e-16 ***\nI(nearest_hospital_m^2)        8.235e-03  7.092e-04  11.611  < 2e-16 ***\ncrime_count:unemployment_rate  4.012e+00  5.686e-01   7.056 1.76e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 129000 on 24669 degrees of freedom\n  (896 observations deleted due to missingness)\nMultiple R-squared:  0.6117,\tAdjusted R-squared:  0.6114 \nF-statistic:  2045 on 19 and 24669 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\nThis final model adds categorical variables and an interaction between crime and unemployment to capture contextual effects. The fit improves slightly again (R² ≈ 0.61). Structural patterns remain stable: larger and newer homes with more bathrooms are worth more, and aging reduces value but at a slowing rate.\n\nNeighborhood effects also stay consistent—higher income and education raise prices, while higher unemployment and larger Black population shares lower them. In areas with higher unemployment, housing prices are less sensitive to crime; in contrast, in areas with lower unemployment and stronger economic conditions, crime has a larger negative impact on housing values.\n\nAdding location and amenity dummies refines spatial interpretation. Properties in Center City and those with garages sell for more, while areas with fewer recreation facilities are valued lower. Proximity to hospitals and transit access continue to show positive associations with housing value.\n\n## Phase 5: Model Validation\n\n### 1. Use 10-fold cross-validation\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_data <- opa_census %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    sale_price, total_livable_area, number_of_bedrooms,\n    number_of_bathrooms, house_age,\n    median_income, ba_rate, unemployment_rate, black_share,\n    crime_count, transit_count, recreation_count, recreation_dummy,\n    nearest_hospital_m, center_city_dummy, has_garage\n  ) %>%\n  filter(complete.cases(.))\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfml1 <- sale_price ~\n  total_livable_area + number_of_bedrooms +\n  number_of_bathrooms + house_age + I(house_age^2)\n\nfml2 <- sale_price ~\n  total_livable_area + number_of_bedrooms +\n  number_of_bathrooms + house_age + I(house_age^2) + \n  median_income + ba_rate + log(unemployment_rate + 1) + black_share\n\nfml3 <- sale_price ~ total_livable_area + number_of_bedrooms +\n  number_of_bathrooms + house_age + I(house_age^2) +\n  median_income + ba_rate + log(unemployment_rate+1) + black_share +\n  crime_count + I(crime_count^2) + \n  transit_count + recreation_count + nearest_hospital_m + I(nearest_hospital_m^2)\n\nfml4 <- sale_price ~ \n  total_livable_area + number_of_bedrooms +\n  number_of_bathrooms + house_age + I(house_age^2) +\n  median_income + ba_rate + crime_count*unemployment_rate + black_share + \n  has_garage + center_city_dummy + recreation_dummy +\n  transit_count + nearest_hospital_m + I(nearest_hospital_m^2)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\ncv_control <- trainControl(method = \"cv\", number = 10, savePredictions = \"final\")\n\nm1 <- train(fml1, data = model_data, method = \"lm\", trControl = cv_control)\nm2 <- train(fml2, data = model_data, method = \"lm\", trControl = cv_control)\nm3 <- train(fml3, data = model_data, method = \"lm\", trControl = cv_control)\nm4 <- train(fml4, data = model_data, method = \"lm\", trControl = cv_control)\n```\n:::\n\n\nThis section evaluates model performance using 10-fold cross-validation to ensure generalizability. The dataset was split into ten equal subsets: in each iteration, nine folds trained the model while the remaining one tested it. This process repeated ten times so every observation served once as validation data. The caret::train() function handled resampling automatically through trainControl(method = \"cv\", number = 10), producing stable estimates of RMSE, MAE, and R² for each model specification.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults <- resamples(list(\n  Model1 = m1, Model2 = m2, Model3 = m3, Model4 = m4\n))\nsummary(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nsummary.resamples(object = results)\n\nModels: Model1, Model2, Model3, Model4 \nNumber of resamples: 10 \n\nMAE \n            Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA's\nModel1 103832.37 105851.22 106517.63 106328.38 106921.93 108152.06    0\nModel2  79425.48  81272.40  81915.61  82093.29  82932.69  86451.81    0\nModel3  77409.32  79949.03  81598.75  81708.58  84257.63  85577.85    0\nModel4  78644.93  80083.13  80844.30  81139.03  82327.48  83757.55    0\n\nRMSE \n           Min.  1st Qu.   Median     Mean  3rd Qu.     Max. NA's\nModel1 145350.1 152411.8 153331.8 153662.0 156080.2 159735.1    0\nModel2 122545.9 125892.2 129781.0 130385.0 133188.4 141634.3    0\nModel3 117575.6 121104.8 131024.7 129307.9 136081.8 142036.6    0\nModel4 119231.8 126158.4 127392.3 129018.7 130930.4 139698.6    0\n\nRsquared \n            Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA's\nModel1 0.4136413 0.4421692 0.4515556 0.4497851 0.4556238 0.4862556    0\nModel2 0.5605534 0.5835312 0.6031830 0.6033292 0.6258022 0.6362505    0\nModel3 0.5374865 0.5799484 0.6114265 0.6099480 0.6449153 0.6753661    0\nModel4 0.5748278 0.5996610 0.6132781 0.6116480 0.6262643 0.6538824    0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cross-validation average metrics\nmodel_results <- tibble(\n  Model = c(\"Model 1: Structural Only\", \n            \"Model 2: + Census Variables\", \n            \"Model 3: + Spatial Features\", \n            \"Model 4: + Interactions and Fixed Effects\"),\n  MAE = c(106328, 82093, 81709, 81139),\n  RMSE = c(153662, 130385, 129308, 129019),\n  R2 = c(0.450, 0.603, 0.610, 0.612)\n)\n\nmodel_results %>%\n  gt() %>%\n  fmt_number(columns = c(MAE, RMSE), decimals = 0) %>%\n  fmt_number(columns = R2, decimals = 3) %>%\n  tab_header(\n    title = \"Model Performance (10-Fold Cross Validation)\",\n    subtitle = \"Average metrics across resamples\"\n  ) %>%\n  cols_label(\n    Model = \"Model Specification\",\n    MAE = \"Mean Absolute Error ($)\",\n    RMSE = \"Root Mean Squared Error ($)\",\n    R2 = \"R²\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pdkpbjvqmg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pdkpbjvqmg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pdkpbjvqmg thead, #pdkpbjvqmg tbody, #pdkpbjvqmg tfoot, #pdkpbjvqmg tr, #pdkpbjvqmg td, #pdkpbjvqmg th {\n  border-style: none;\n}\n\n#pdkpbjvqmg p {\n  margin: 0;\n  padding: 0;\n}\n\n#pdkpbjvqmg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pdkpbjvqmg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pdkpbjvqmg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pdkpbjvqmg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pdkpbjvqmg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pdkpbjvqmg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pdkpbjvqmg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pdkpbjvqmg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pdkpbjvqmg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pdkpbjvqmg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pdkpbjvqmg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pdkpbjvqmg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pdkpbjvqmg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pdkpbjvqmg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pdkpbjvqmg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdkpbjvqmg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pdkpbjvqmg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pdkpbjvqmg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pdkpbjvqmg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdkpbjvqmg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pdkpbjvqmg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdkpbjvqmg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pdkpbjvqmg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdkpbjvqmg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pdkpbjvqmg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdkpbjvqmg .gt_left {\n  text-align: left;\n}\n\n#pdkpbjvqmg .gt_center {\n  text-align: center;\n}\n\n#pdkpbjvqmg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pdkpbjvqmg .gt_font_normal {\n  font-weight: normal;\n}\n\n#pdkpbjvqmg .gt_font_bold {\n  font-weight: bold;\n}\n\n#pdkpbjvqmg .gt_font_italic {\n  font-style: italic;\n}\n\n#pdkpbjvqmg .gt_super {\n  font-size: 65%;\n}\n\n#pdkpbjvqmg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pdkpbjvqmg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pdkpbjvqmg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pdkpbjvqmg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pdkpbjvqmg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pdkpbjvqmg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pdkpbjvqmg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pdkpbjvqmg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pdkpbjvqmg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Model Performance (10-Fold Cross Validation)</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Average metrics across resamples</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Model\">Model Specification</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MAE\">Mean Absolute Error ($)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"RMSE\">Root Mean Squared Error ($)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"R2\">R²</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">Model 1: Structural Only</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">106,328</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">153,662</td>\n<td headers=\"R2\" class=\"gt_row gt_right\">0.450</td></tr>\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">Model 2: + Census Variables</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">82,093</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">130,385</td>\n<td headers=\"R2\" class=\"gt_row gt_right\">0.603</td></tr>\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">Model 3: + Spatial Features</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">81,709</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">129,308</td>\n<td headers=\"R2\" class=\"gt_row gt_right\">0.610</td></tr>\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">Model 4: + Interactions and Fixed Effects</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">81,139</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">129,019</td>\n<td headers=\"R2\" class=\"gt_row gt_right\">0.612</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe 10-fold cross-validation results show steady improvement as more variables are added. The structural model explains about 45% of price variation, while adding census data raises accuracy to 60%. Including spatial features gives small but consistent gains, and the final model with interaction and fixed-effect terms reaches the best overall performance (MAE ≈ $81K; RMSE ≈ $129K; R² = 0.61), showing that it captures most location and neighborhood effects on housing prices.\n\n### 2. Predicted vs. Actual Plot for First Model and Final Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_df1 <- opa_census %>%\n  mutate(\n    pred = predict(model1, newdata = opa_census),\n    obs = sale_price\n  ) %>%\n  dplyr::select(pred, obs)\n\nplot_df4 <- opa_census %>%\n  mutate(\n    pred = predict(model4, newdata = opa_census),\n    obs = sale_price\n  ) %>%\n  dplyr::select(pred, obs)\n\nrmse1 <- 153662   # Model 1 RMSE\nr21   <- 0.45     # Model 1 R²\nrmse4 <- 129019   # Model 4 RMSE\nr24   <- 0.61     # Model 4 R²\n\np1 <- ggplot(plot_df1, aes(x = pred, y = obs)) +\n  geom_point(alpha = 0.3, color = \"#E69F00\") +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(\n    title = \"Model 1\",\n    subtitle = paste0(\"RMSE = \", scales::comma(rmse1), \n                      \", R² = \", round(r21, 2))\n  ) +\n  theme_minimal() +\n  coord_fixed()\n\n\np4 <- ggplot(plot_df4, aes(x = pred, y = obs)) +\n  geom_point(alpha = 0.3, color = \"#4682B4\") +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(\n    title = \"Model 4\",\n    subtitle = paste0(\"RMSE = \", scales::comma(rmse4), \n                      \", R² = \", round(r24, 2))\n  ) +\n  theme_minimal() +\n  coord_fixed()\n\np1 + p4 +\n  plot_annotation(\n    title = \"Predicted vs. Actual Sale Prices\",\n    subtitle = \"Comparison between Model 1 and Model 4\",\n    theme = theme(plot.title = element_text(size = 16, face = \"bold\"),\n                  plot.subtitle = element_text(size = 12))\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nModel 4 demonstrates a noticeably better fit than Model 1, with predicted values more tightly clustered around the 45-degree line. The improvement reflects how adding census, spatial, and interaction terms enhances the model’s ability to capture neighborhood-level variation in housing prices. Residual dispersion decreases, though some bias persists at the extremes: high-value properties tend to be slightly underestimated, while low-value ones are sometimes overpredicted. These patterns are common in real-world housing data, where non-market transactions, inheritances, or atypical sales fall outside the scope of typical market dynamics.\n\n### 3. top 5 predictors visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4_std <- lm.beta(model4)\n\ncoef_std <- broom::tidy(model4_std) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(Standardized = model4_std$standardized.coefficients[term])\n\ntop5_std <- coef_std %>%\n  arrange(desc(abs(Standardized))) %>%\n  slice(1:10)\n\nkable(\n  top5_std %>%\n    dplyr::select(term, estimate, Standardized, std.error, statistic, p.value) %>%\n    mutate(across(where(is.numeric), ~ round(., 3))),\n  caption = \"Top 10 Standardized Coefficients from Model 4\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Standardized Coefficients from Model 4\n\n|term                    |   estimate| Standardized| std.error| statistic| p.value|\n|:-----------------------|----------:|------------:|---------:|---------:|-------:|\n|total_livable_area      |    139.756|        0.353|     1.898|    73.628|       0|\n|house_age               |  -2138.542|       -0.319|   101.520|   -21.065|       0|\n|I(house_age^2)          |     10.533|        0.236|     0.665|    15.828|       0|\n|nearest_hospital_m      |    -42.134|       -0.207|     3.313|   -12.717|       0|\n|number_of_bathrooms     |  59752.834|        0.200|  1562.682|    38.237|       0|\n|median_income           |      1.259|        0.195|     0.046|    27.173|       0|\n|I(nearest_hospital_m^2) |      0.008|        0.181|     0.001|    11.611|       0|\n|ba_rate                 |   2405.764|        0.143|   124.828|    19.273|       0|\n|recreation_dummyLow     | -54254.808|       -0.131|  4947.201|   -10.967|       0|\n|recreation_dummyMedium  | -45676.480|       -0.109|  4897.261|    -9.327|       0|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop5_std %>%\n  mutate(term = reorder(term, abs(Standardized))) %>%\n  ggplot(aes(x = term, y = Standardized, fill = Standardized > 0)) +\n  geom_col(width = 0.6, show.legend = FALSE) +\n  coord_flip() +\n  geom_text(aes(label = round(Standardized, 3)),\n            hjust = ifelse(top5_std$Standardized > 0, -0.1, 1.1),\n            size = 3.8) +\n  scale_fill_manual(values = c(\"skyblue\", \"hotpink\")) +\n  labs(\n    title = \"Top 10 Standardized Coefficients from Model 4\",\n    x = \"\",\n    y = \"Standardized Coefficient (β)\"\n  ) +\n  theme_minimal(base_size = 13) +\n  geom_hline(yintercept = 0, color = \"black\", linewidth = 0.8) +\n  expand_limits(y = c(-max(abs(top5_std$Standardized)) * 1.2, \n                      max(abs(top5_std$Standardized)) * 1.2)) +\n  theme(\n    plot.title = element_text(face = \"bold\", hjust = 0.5),\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\nThe standardized coefficients show which variables have the strongest relative influence on housing prices after accounting for differences in measurement units. Total livable area has the largest positive effect, meaning larger homes consistently sell for more. House age shows the strongest negative relationship—older properties tend to be less valuable—but the positive squared term indicates that this decline slows with age. Proximity to hospitals also matters: homes closer to medical facilities are priced higher, while distance reduces value. Among neighborhood and amenity factors, higher education levels (BA rate) and income raise prices, whereas limited recreational access slightly lowers them.\n\n## Phase 6:  Model Diagnostics\n### 1. residual plot, QQ plot, Cook's distance\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n\n# 1. Residuals vs Fitted\nplot(model4, which = 1, main = \"Residuals vs Fitted\")\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# 2. Normal Q-Q\nplot(model4, which = 2, main = \"Q-Q Plot\")\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-30-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# 3. Cook’s distance\nplot(model4, which = 4, main = \"Cook’s Distance\")\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-30-3.png){width=672}\n:::\n:::\n\n\nThe residuals vs. fitted plot shows a roughly symmetric spread around zero but with noticeable heteroscedasticity—larger variance among high-priced properties, showing that extreme prices remain difficult to predict precisely. The Q–Q plot indicates some heavy tails and outliers. In real-world housing data, perfect normality and constant variance are rarely achievable, so these deviations remain within a reasonable range for practical modeling.\n\nThe Cook’s Distance plot further supports this assessment. Most observations exert minimal influence on the fitted model, though a few high-leverage points stand out. These likely correspond to unusually expensive or unique properties that differ substantially from the bulk of the dataset. While such influential cases can slightly affect coefficient estimates, their limited number suggests that the overall model remains stable and reliable.\n\n### 2. Mean Residual by Neighborhood\n\n::: {.cell}\n\n```{.r .cell-code}\nopa_census$pred_price <- predict(model4, newdata = opa_census)\n\nopa_ward <- st_join(opa_census, wards[\"ward_num\"])\n\nward_summary <- opa_ward %>%\n  st_drop_geometry() %>%\n  group_by(ward_num) %>%\n  summarise(\n    mean_actual = mean(sale_price, na.rm = TRUE),\n    mean_pred = mean(pred_price, na.rm = TRUE),\n    median_pred = median(pred_price, na.rm = TRUE),\n    n_properties = n()\n  ) %>%\n  mutate(residual_mean = mean_actual - mean_pred) %>% \n  arrange(desc(residual_mean))\n\nhead(ward_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  ward_num mean_actual mean_pred median_pred n_properties residual_mean\n  <chr>          <dbl>     <dbl>       <dbl>        <int>         <dbl>\n1 30           640680.   485118.     479847.          505       155562.\n2 9            626051.   499829.     464823.          217       126222.\n3 14           422417.   343372.     295923.           51        79044.\n4 8            484681.   405894.     397665.          593        78787.\n5 27           403270.   335831.     311875.           93        67439.\n6 2            558185.   503658.     488557.          563        54527.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nward_plot_data <- wards %>%\n  left_join(ward_summary, by = \"ward_num\")\n\nggplot(ward_plot_data) +\n  geom_sf(aes(fill = residual_mean), color = \"white\", size = 0.2) +\n  scale_fill_gradient2(\n    low = \"#4575B4\",\n    mid = \"white\",\n    high = \"#D73027\",\n    midpoint = 0,\n    labels = scales::label_dollar()\n  ) +\n  labs(\n    title = \"Mean Prediction Residuals by Ward\",\n    subtitle = \"Positive = Underestimation | Negative = Overestimation\",\n    fill = \"Actual - Predicted\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_nolog_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n## Phase 7: Conclusions & Recommendations  \nThis project predicts housing sale prices in Philadelphia and shows that structural inequality in the city is spatially organized, with high-value neighborhoods concentrated in the central, northeast, and northwestern parts, and lower-value areas clustered in the north and west.\n\nThe model shows that actual sale prices in high-value neighborhoods are consistently higher than predicted, while those in lower-income and high-unemployment areas tend to be slightly lower than predicted. This residual pattern indicates a potential bias in the city’s property assessment system, where wealthier neighborhoods may be undertaxed and disadvantaged ones overtaxed.\n\nIn neighborhoods with high unemployment and crime, the model shows that housing markets no longer respond to safety improvements. Simply adding policing or security programs does not raise property values because the underlying economic conditions remain weak. For safety investments to be effective, policies should focus on rebuilding the local economic base by expanding job opportunities, supporting small businesses, and improving public infrastructure to make these neighborhoods worth to invest.\n\nThe model primarily captures spatial variation but performs less accurately for properties with sale prices above one million dollars. Some public datasets contain missing or inconsistent records, which may introduce minor systematic bias. Future research should integrate temporal dynamics and machine learning methods to better predict properties at both the lower and upper ends of the sale price distribution.\n\nTo promote spatial equity, policy should expand affordable and mixed-income housing in high-value districts through inclusionary zoning and other incentives, while improving transit, recreational spaces, and essential urban amenities—such as schools, healthcare facilities, and public services—in underserved neighborhoods, so that opportunity and growth are not confined to a few areas.\n",
    "supporting": [
      "appendix_nolog_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}